// Our own talent calculator for WoW Forever. The talent names, trees and point thresholds below
// are the real WoW Forever beta data (read from Icy Veins' WoW Forever talent calculators, updated
// for the beta — not vanilla WoW's talents, and not guessed). Each tree has 7 tiers, unlocking
// every 5 points spent in that tree (0/5/10/15/20/25/30). Effect descriptions (the `d` field) are
// our own short, original wording — condensed from what each talent's name and context imply, not
// copied from any tooltip. Format: { t: tier, name, max: maxRank, d: short effect }
//
// General talent-system facts (level 10 start, extra 16-point choice, dual spec at 40, etc.) and
// other per-class mechanic changes that don't show up as tree nodes are tracked separately in
// FOREVER_CHANGES, sourced from wowforever.sk's own news posts and class beta-overview pages.

export const TALENT_TREES = {
  warrior: {
    trees: [
      { key: 'arms', name: 'Arms', icon: 'sword', talents: [
        { t: 0, name: 'Improved Heroic Strike', max: 3, d: 'Strengthens the effect of Heroic Strike.' },
        { t: 0, name: 'Deflection', max: 5, d: 'Increases your chance to parry.' },
        { t: 0, name: 'Improved Rend', max: 3, d: 'Strengthens the effect of Rend.' },
        { t: 1, name: 'Improved Charge', max: 2, d: 'Strengthens the effect of Charge.' },
        { t: 1, name: 'Improved Tactical Mastery', max: 5, d: 'Strengthens the effect of Tactical Mastery.' },
        { t: 1, name: 'Improved Overpower', max: 2, d: 'Strengthens the effect of Overpower.' },
        { t: 2, name: 'Anger Management', max: 1, d: 'Generates 1 rage every 3 sec automatically, even out of combat.' },
        { t: 2, name: 'Deep Wounds', max: 3, d: 'Your critical strikes cause the target to bleed over several seconds.' },
        { t: 3, name: 'Spearing Strike', max: 1, d: 'An instant thrust that deals bonus damage and cannot be dodged or parried.' },
        { t: 3, name: 'Two-Handed Weapon Specialization', max: 3, d: 'Increases your damage with Two-Handed Weapon per rank.' },
        { t: 3, name: 'Impale', max: 2, d: 'Increases the critical strike damage bonus of your abilities.' },
        { t: 4, name: 'Bloodthrill', max: 5, d: 'Your critical strikes have a chance to grant a burst of extra rage.' },
        { t: 4, name: 'Sweeping Strikes', max: 1, d: 'Your next 5 melee attacks also strike a second nearby enemy.' },
        { t: 4, name: 'Weaponmaster', max: 5, d: 'Your special attacks have a chance to not trigger their cooldown.' },
        { t: 5, name: 'Improved Slam', max: 2, d: 'Strengthens the effect of Slam.' },
        { t: 5, name: 'Improved Hamstring', max: 3, d: 'Strengthens the effect of Hamstring.' },
        { t: 6, name: 'Mortal Strike', max: 1, d: 'A vicious strike that reduces healing received by the target for 10 sec.' },
      ] },
      { key: 'fury', name: 'Fury', icon: 'flame-fist', talents: [
        { t: 0, name: 'Booming Voice', max: 5, d: 'Increases the radius and duration of your shout effects.' },
        { t: 0, name: 'Cruelty', max: 5, d: 'Increases your critical strike chance.' },
        { t: 1, name: 'Lingering Rage', max: 5, d: 'You lose rage more slowly while out of combat.' },
        { t: 1, name: 'Unbridled Wrath', max: 5, d: 'Your successful melee attacks have a chance to generate extra rage.' },
        { t: 2, name: 'Furious Precision', max: 3, d: 'Increases your critical strike chance with Fury abilities.' },
        { t: 2, name: 'Piercing Howl', max: 1, d: 'An AoE shout that snares all nearby enemies.' },
        { t: 2, name: 'Blood Craze', max: 3, d: 'After being hit, you regenerate health over the next few seconds.' },
        { t: 3, name: 'Dual Wield Specialization', max: 5, d: 'Increases your damage with Dual Wield per rank.' },
        { t: 3, name: 'Raging Blows', max: 1, d: 'An instant strike, usable only while Enraged, that deals heavy extra damage.' },
        { t: 3, name: 'Enrage', max: 5, d: 'Taking damage has a chance to increase your damage done for a few seconds.' },
        { t: 3, name: 'Improved Execute', max: 2, d: 'Strengthens the effect of Execute.' },
        { t: 4, name: 'Improved Berserker Rage', max: 2, d: 'Strengthens the effect of Berserker Rage.' },
        { t: 4, name: 'Death Wish', max: 1, d: 'Increases physical damage done, at the cost of increased damage taken, for 30 sec.' },
        { t: 4, name: 'Improved Intercept', max: 2, d: 'Strengthens the effect of Intercept.' },
        { t: 5, name: 'Flurry', max: 5, d: 'After a critical strike, your attack speed increases for your next few swings.' },
        { t: 5, name: 'Gore Drinker', max: 2, d: 'Your Bloodthirst and Whirlwind have a chance to heal you.' },
        { t: 6, name: 'Bloodthirst', max: 1, d: 'An instant strike that deals damage based on your attack power and heals you for a portion of the damage dealt.' },
      ] },
      { key: 'prot', name: 'Protection', icon: 'shield', talents: [
        { t: 0, name: 'Improved Bloodrage', max: 2, d: 'Strengthens the effect of Bloodrage.' },
        { t: 0, name: 'Shield Specialization', max: 5, d: 'Increases your damage with Shield per rank.' },
        { t: 0, name: 'Iron Will', max: 5, d: 'Increases your resistance to stun effects.' },
        { t: 1, name: 'Anticipation', max: 5, d: 'Increases your chance to dodge.' },
        { t: 1, name: 'Improved Revenge', max: 3, d: 'Strengthens the effect of Revenge.' },
        { t: 1, name: 'Improved Thunder Clap', max: 3, d: 'Strengthens the effect of Thunder Clap.' },
        { t: 2, name: 'Last Stand', max: 1, d: 'Temporarily increases your maximum health by 30%.' },
        { t: 2, name: 'Master of Defense', max: 2, d: 'Increases your chance to block attacks.' },
        { t: 2, name: 'Improved Disarm', max: 3, d: 'Strengthens the effect of Disarm.' },
        { t: 2, name: 'Defiance', max: 3, d: 'Increases the threat you generate while in Defensive Stance.' },
        { t: 3, name: 'Improved Sunder Armor', max: 3, d: 'Strengthens the effect of Sunder Armor.' },
        { t: 3, name: 'Vanguard', max: 1, d: 'Your Shield Block also grants a stacking damage reduction for its duration.' },
        { t: 3, name: 'Improved Shield Bash', max: 2, d: 'Strengthens the effect of Shield Bash.' },
        { t: 4, name: 'Improved Shield Wall', max: 2, d: 'Strengthens the effect of Shield Wall.' },
        { t: 4, name: 'Concussion Blow', max: 1, d: 'A shield bash that stuns the target for a few seconds.' },
        { t: 4, name: 'Focused Rage', max: 3, d: 'Reduces the rage cost of your special attacks.' },
        { t: 5, name: 'Bastion', max: 5, d: 'Increases the amount of damage your Shield Block absorbs.' },
        { t: 6, name: 'Shield Slam', max: 1, d: 'Slams the target with your shield, dealing damage based on your block value.' },
      ] },
    ],
  },
  paladin: {
    trees: [
      { key: 'holy', name: 'Holy', icon: 'sunburst', talents: [
        { t: 0, name: 'Divine Strength', max: 5, d: 'Increases your Strength.' },
        { t: 0, name: 'Divine Intellect', max: 5, d: 'Increases your Intellect.' },
        { t: 1, name: 'Healing Light', max: 3, d: 'Increases the healing done by your Holy Light and Flash of Light.' },
        { t: 1, name: 'Spiritual Focus', max: 2, d: 'Gives you a chance to not be interrupted while casting healing spells.' },
        { t: 1, name: 'Improved Seals', max: 3, d: 'Strengthens the effect of Seals.' },
        { t: 1, name: 'Unyielding Faith', max: 2, d: 'Increases your resistance to Fear and Horror effects.' },
        { t: 2, name: 'Voice of Truth', max: 1, d: 'Your Judgement also restores mana to party members within its radius.' },
        { t: 2, name: 'Reverence', max: 3, d: 'Reduces the mana cost of your Blessing and Seal spells.' },
        { t: 2, name: 'Purifying Power', max: 2, d: 'Increases the critical strike chance of your Holy spells.' },
        { t: 3, name: 'Infusion of Light', max: 2, d: 'Reduces the cast time of your next Holy Light or Flash of Light after a critical heal.' },
        { t: 3, name: 'Illumination', max: 5, d: 'Critical heals refund a portion of their mana cost.' },
        { t: 3, name: 'Divine Favor', max: 1, d: 'Your next heal or Holy Shock is guaranteed to critically strike.' },
        { t: 4, name: 'Divine Precision', max: 3, d: 'Increases your chance to hit with spells and attacks.' },
        { t: 4, name: 'Holy Shock', max: 1, d: 'An instant burst of holy energy that heals an ally or damages an enemy.' },
        { t: 4, name: 'Consecrated Ground', max: 2, d: 'Standing in your Consecration grants a defensive bonus.' },
        { t: 5, name: 'Holy Power', max: 5, d: 'Increases the critical strike chance of your healing spells.' },
        { t: 6, name: 'Light\'s Vigil', max: 1, d: 'Your heals occasionally trigger a wave of light that heals nearby injured allies.' },
      ] },
      { key: 'prot', name: 'Protection', icon: 'shield', talents: [
        { t: 0, name: 'Toughness', max: 5, d: 'Increases your armor value from items.' },
        { t: 0, name: 'Redoubt', max: 5, d: 'After blocking an attack, your block chance is increased for a few seconds.' },
        { t: 1, name: 'Precision', max: 3, d: 'Increases your chance to hit.' },
        { t: 1, name: 'Guardian\'s Favor', max: 2, d: 'Reduces the cooldown and increases the range of your Hand spells.' },
        { t: 1, name: 'Anticipation', max: 5, d: 'Increases your chance to dodge.' },
        { t: 2, name: 'Improved Seal of Fury', max: 1, d: 'Adds a stacking haste effect to Seal of Fury.' },
        { t: 2, name: 'Improved Righteous Fury', max: 3, d: 'Strengthens the effect of Righteous Fury.' },
        { t: 2, name: 'Shield Specialization', max: 3, d: 'Increases your damage with Shield per rank.' },
        { t: 2, name: 'Sacred Duty', max: 2, d: 'Reduces the cooldown of your Divine Protection and Divine Shield.' },
        { t: 3, name: 'Swift Judgement', max: 1, d: 'Reduces the cooldown of Judgement.' },
        { t: 3, name: 'One-Handed Weapon Specialization', max: 3, d: 'Increases your damage with One-Handed Weapon per rank.' },
        { t: 3, name: 'Improved Hammer of Justice', max: 3, d: 'Strengthens the effect of Hammer of Justice.' },
        { t: 4, name: 'Templar\'s Bulwark', max: 1, d: 'Blocking an attack has a chance to stun the attacker.' },
        { t: 4, name: 'Reckoning', max: 5, d: 'Gives you a chance for an extra melee attack when you are struck in combat.' },
        { t: 5, name: 'Iron Creed', max: 5, d: 'Increases your armor value from items.' },
        { t: 6, name: 'Holy Shield', max: 1, d: 'Increases your block chance, and blocked attacks damage the attacker.' },
      ] },
      { key: 'ret', name: 'Retribution', icon: 'warhammer', talents: [
        { t: 0, name: 'Deflection', max: 5, d: 'Increases your chance to parry.' },
        { t: 0, name: 'Benediction', max: 5, d: 'Reduces the mana cost of your spells.' },
        { t: 1, name: 'Improved Judgement', max: 2, d: 'Strengthens the effect of Judgement.' },
        { t: 1, name: 'Holy Conduit', max: 2, d: 'Increases the holy damage of your Judgement and Seal effects.' },
        { t: 1, name: 'Conviction', max: 5, d: 'Increases your critical strike chance.' },
        { t: 2, name: 'Vindication', max: 3, d: 'Your attacks reduce the target\'s attack power or spell damage for a time.' },
        { t: 2, name: 'Sanctified Judgement', max: 3, d: 'Reduces the mana cost and cooldown of Judgement.' },
        { t: 2, name: 'Seal of Command', max: 1, d: 'A new seal: grants a chance for an extra attack whenever you land a hit.' },
        { t: 2, name: 'Pursuit of Justice', max: 2, d: 'Increases your movement speed while a Seal is active.' },
        { t: 3, name: 'Eye for an Eye', max: 2, d: 'Reflects a portion of melee and spell critical strikes back at the attacker.' },
        { t: 3, name: 'Sacred Arbiter', max: 1, d: 'Your Judgement deals bonus holy damage based on your attack power.' },
        { t: 4, name: 'Two-Handed Weapon Specialization', max: 3, d: 'Increases your damage with Two-Handed Weapon per rank.' },
        { t: 4, name: 'Vengeance', max: 3, d: 'Increases your damage and healing done against Humans, Orcs, Demons and Undead.' },
        { t: 4, name: 'Repentance', max: 1, d: 'Puts the target into a state of stasis for a short time.' },
        { t: 5, name: 'Champion of the Light', max: 3, d: 'Increases the damage of your Retribution abilities.' },
        { t: 5, name: 'Instrument of Law', max: 2, d: 'Your Judgement has a chance to grant bonus holy damage on your next attack.' },
        { t: 6, name: 'Twist of Light', max: 1, d: 'Your melee critical strikes have a chance to heal a nearby injured ally.' },
      ] },
    ],
  },
  hunter: {
    trees: [
      { key: 'bm', name: 'Beast Mastery', icon: 'paw', talents: [
        { t: 0, name: 'Deadly Aspects', max: 5, d: 'Increases the effect of your Aspect spells.' },
        { t: 0, name: 'Endurance Training', max: 5, d: 'Increases your pet\'s maximum health.' },
        { t: 1, name: 'Focused Fire', max: 2, d: 'Increases the critical strike chance of your pet\'s attacks.' },
        { t: 1, name: 'Improved Aspect of the Monkey', max: 3, d: 'Strengthens the effect of Aspect of the Monkey.' },
        { t: 1, name: 'Pathfinding', max: 2, d: 'Increases your movement speed while a Hunter Aspect is active.' },
        { t: 1, name: 'Improved Revive Pet', max: 2, d: 'Strengthens the effect of Revive Pet.' },
        { t: 2, name: 'Bestial Swiftness', max: 1, d: 'Increases your pet\'s movement speed.' },
        { t: 2, name: 'Unleashed Fury', max: 5, d: 'Increases the damage done by your pet.' },
        { t: 3, name: 'Improved Mend Pet', max: 2, d: 'Strengthens the effect of Mend Pet.' },
        { t: 3, name: 'Ferocity', max: 5, d: 'Reduces the cooldown on your pet\'s special abilities.' },
        { t: 3, name: 'Summon Hawk', max: 1, d: 'Summons a loyal hawk companion that assists you in combat.' },
        { t: 4, name: 'Spirit Bond', max: 2, d: 'You and your pet passively regenerate health over time while out of combat.' },
        { t: 4, name: 'Intimidation', max: 1, d: 'Commands your pet to intimidate the target, stunning it briefly.' },
        { t: 4, name: 'Bestial Discipline', max: 2, d: 'Increases your pet\'s maximum Focus.' },
        { t: 5, name: 'Frenzy', max: 5, d: 'After a critical strike, your pet\'s attack speed increases for a few seconds.' },
        { t: 6, name: 'Bestial Wrath', max: 1, d: 'Your pet goes berserk, dealing much more damage and becoming immune to crowd control for 18 sec.' },
      ] },
      { key: 'mm', name: 'Marksmanship', icon: 'bow', talents: [
        { t: 0, name: 'Hawk Eye', max: 3, d: 'Increases the range of your ranged weapon attacks.' },
        { t: 0, name: 'Improved Concussive Shot', max: 5, d: 'Strengthens the effect of Concussive Shot.' },
        { t: 0, name: 'Lethal Attacks', max: 5, d: 'Increases the critical strike chance of your ranged attacks.' },
        { t: 1, name: 'Improved Stings', max: 3, d: 'Strengthens the effect of Stings.' },
        { t: 1, name: 'Efficiency', max: 5, d: 'Reduces the mana cost of your abilities.' },
        { t: 1, name: 'Careful Aim', max: 5, d: 'Increases your critical strike chance with ranged attacks against targets above 70% health.' },
        { t: 2, name: 'Rapid Killing', max: 2, d: 'Killing a target reduces the cooldown of Rapid Fire.' },
        { t: 2, name: 'Improved Arcane Shot', max: 5, d: 'Strengthens the effect of Arcane Shot.' },
        { t: 2, name: 'Lone Wolf', max: 1, d: 'Increases your damage done while you have no active pet.' },
        { t: 3, name: 'Trueshot Aura', max: 1, d: 'An aura that increases the attack power of your entire party.' },
        { t: 3, name: 'Mortal Shots', max: 5, d: 'Increases the critical strike damage of your ranged weapon attacks.' },
        { t: 4, name: 'Rapid Recuperation', max: 2, d: 'Rapid Fire also regenerates mana while active.' },
        { t: 4, name: 'Barrage', max: 3, d: 'Reduces the threat generated by your ranged attacks.' },
        { t: 4, name: 'Scatter Shot', max: 1, d: 'A close-range shot that disorients the target, interrupting spellcasting.' },
        { t: 5, name: 'Ranged Weapon Specialization', max: 5, d: 'Increases your damage with Ranged Weapon per rank.' },
        { t: 6, name: 'Sniper Shot', max: 1, d: 'A powerful finishing shot usable only against targets below 20% health.' },
      ] },
      { key: 'surv', name: 'Survival', icon: 'trap', talents: [
        { t: 0, name: 'Improved Tracking', max: 5, d: 'Strengthens the effect of Tracking.' },
        { t: 0, name: 'Deflection', max: 5, d: 'Increases your chance to parry.' },
        { t: 1, name: 'Entrapment', max: 5, d: 'Your traps have a chance to root the target in place.' },
        { t: 1, name: 'Savage Strikes', max: 2, d: 'Increases the critical strike chance of your melee attacks.' },
        { t: 1, name: 'Survivalist', max: 5, d: 'Increases your maximum health.' },
        { t: 1, name: 'Improved Wing Clip', max: 3, d: 'Strengthens the effect of Wing Clip.' },
        { t: 2, name: 'Clever Traps', max: 2, d: 'Increases the duration of your traps\' effects.' },
        { t: 2, name: 'Surefooted', max: 3, d: 'Reduces the duration of movement-impairing effects used against you.' },
        { t: 2, name: 'Deterrence', max: 1, d: 'Massively increases your dodge and parry chance for a few seconds.' },
        { t: 3, name: 'Survival Tactics', max: 2, d: 'Reduces the chance you\'ll be critically hit by melee attacks.' },
        { t: 3, name: 'Predator\'s Edge', max: 5, d: 'Increases the damage done by your ranged weapon attacks.' },
        { t: 3, name: 'Counterattack', max: 1, d: 'After a dodge or parry, your next melee attack deals bonus damage.' },
        { t: 4, name: 'Resourcefulness', max: 2, d: 'Reduces the cooldown and mana cost of your trap spells.' },
        { t: 4, name: 'Expose Prey', max: 2, d: 'Your ranged attacks have a chance to expose the target\'s armor.' },
        { t: 4, name: 'Survivalist\'s Discipline', max: 2, d: 'Reduces damage taken while Feign Death is on cooldown.' },
        { t: 4, name: 'Strider Kick', max: 1, d: 'A kick that interrupts spellcasting and briefly slows the target.' },
        { t: 5, name: 'Lightning Reflexes', max: 5, d: 'Increases your chance to dodge attacks.' },
        { t: 6, name: 'Lacerating Strikes', max: 1, d: 'Your bleed effects have a chance to deal a burst of additional damage.' },
      ] },
    ],
  },
  rogue: {
    trees: [
      { key: 'assa', name: 'Assassination', icon: 'dagger-drip', talents: [
        { t: 0, name: 'Improved Gouge', max: 3, d: 'Strengthens the effect of Gouge.' },
        { t: 0, name: 'Remorseless Attacks', max: 2, d: 'Increases damage done to targets below 20% health.' },
        { t: 0, name: 'Malice', max: 5, d: 'Increases your critical strike chance.' },
        { t: 1, name: 'Ruthlessness', max: 3, d: 'Finishing moves have a chance to grant a combo point back.' },
        { t: 1, name: 'Murder', max: 2, d: 'Increases your damage done against Humanoids and Beasts.' },
        { t: 1, name: 'Improved Slice and Dice', max: 3, d: 'Strengthens the effect of Slice and Dice.' },
        { t: 2, name: 'Relentless Strikes', max: 1, d: 'Finishing moves have a chance to restore energy.' },
        { t: 2, name: 'Improved Expose Armor', max: 2, d: 'Strengthens the effect of Expose Armor.' },
        { t: 2, name: 'Lethality', max: 5, d: 'Increases the critical strike damage of Sinister Strike and Backstab.' },
        { t: 3, name: 'Vile Poisons', max: 5, d: 'Increases the damage done by your poisons.' },
        { t: 3, name: 'Cold Blood', max: 1, d: 'Your next attack is guaranteed to be a critical strike.' },
        { t: 3, name: 'Improved Poisons', max: 5, d: 'Strengthens the effect of Poisons.' },
        { t: 4, name: 'Vigor', max: 2, d: 'Increases your maximum energy.' },
        { t: 4, name: 'Mutilate', max: 1, d: 'A vicious double stab from stealth that strikes with both weapons at once.' },
        { t: 4, name: 'Improved Kidney Shot', max: 2, d: 'Strengthens the effect of Kidney Shot.' },
        { t: 5, name: 'Seal Fate', max: 5, d: 'Critical strikes that award combo points grant an extra combo point.' },
        { t: 6, name: 'Venom', max: 1, d: 'Your poisons have a chance to deal a burst of extra damage on application.' },
      ] },
      { key: 'combat', name: 'Combat', icon: 'twin-blades', talents: [
        { t: 0, name: 'Improved Eviscerate', max: 3, d: 'Strengthens the effect of Eviscerate.' },
        { t: 0, name: 'Improved Sinister Strike', max: 2, d: 'Strengthens the effect of Sinister Strike.' },
        { t: 0, name: 'Lightning Reflexes', max: 5, d: 'Increases your chance to dodge attacks.' },
        { t: 1, name: 'Puncturing Wounds', max: 3, d: 'Increases the damage of your Sinister Strike and Backstab.' },
        { t: 1, name: 'Deflection', max: 3, d: 'Increases your chance to parry.' },
        { t: 1, name: 'Precision', max: 3, d: 'Increases your chance to hit.' },
        { t: 2, name: 'Endurance', max: 2, d: 'Increases your maximum health.' },
        { t: 2, name: 'Riposte', max: 1, d: 'A powerful counterattack available after a successful parry.' },
        { t: 2, name: 'Improved Sprint', max: 2, d: 'Strengthens the effect of Sprint.' },
        { t: 3, name: 'Improved Kick', max: 2, d: 'Strengthens the effect of Kick.' },
        { t: 3, name: 'Flawless Execution', max: 1, d: 'Execute no longer costs energy when used below 20% target health.' },
        { t: 3, name: 'Dual Wield Specialization', max: 5, d: 'Increases your damage with Dual Wield per rank.' },
        { t: 4, name: 'Blade Flurry', max: 1, d: 'Your melee attacks also strike a nearby second target for a short time.' },
        { t: 4, name: 'Hack and Slash', max: 5, d: 'Increases your chance to land a critical strike with melee weapons.' },
        { t: 5, name: 'Weapon Expertise', max: 2, d: 'Reduces the chance your attacks will be dodged or parried.' },
        { t: 5, name: 'Aggression', max: 3, d: 'Increases the damage done by your finishing moves.' },
        { t: 6, name: 'Adrenaline Rush', max: 1, d: 'Doubles your energy regeneration for a short time.' },
      ] },
      { key: 'sub', name: 'Subtlety', icon: 'mask', talents: [
        { t: 0, name: 'Camouflage', max: 5, d: 'Reduces the chance you\'ll be detected while stealthed.' },
        { t: 0, name: 'Master of Deception', max: 3, d: 'Increases your stealth detection avoidance.' },
        { t: 0, name: 'Opportunity', max: 2, d: 'Increases damage dealt while attacking from stealth.' },
        { t: 1, name: 'Setup', max: 3, d: 'Increases the duration of your Sap and Gouge effects.' },
        { t: 1, name: 'Elusiveness', max: 2, d: 'Reduces the cooldown of Cloak of Shadows and Vanish.' },
        { t: 1, name: 'Dirty Tricks', max: 2, d: 'Reduces the energy cost of Blind, Gouge and Sap.' },
        { t: 1, name: 'Improved Ambush', max: 3, d: 'Strengthens the effect of Ambush.' },
        { t: 2, name: 'Initiative', max: 3, d: 'Grants bonus combo points when you land the opening attack from stealth.' },
        { t: 2, name: 'Ghostly Strike', max: 1, d: 'An instant strike that increases your dodge chance for a few seconds.' },
        { t: 2, name: 'Improved Distract', max: 2, d: 'Strengthens the effect of Distract.' },
        { t: 3, name: 'Heightened Senses', max: 2, d: 'Increases your stealth detection.' },
        { t: 3, name: 'Premeditation', max: 1, d: 'From stealth, instantly gain 2 combo points on your target.' },
        { t: 3, name: 'Serrated Blades', max: 3, d: 'Increases the damage of your finishing moves.' },
        { t: 4, name: 'Dirty Deeds', max: 2, d: 'Increases damage done against targets below 35% health.' },
        { t: 4, name: 'Preparation', max: 1, d: 'Instantly resets the cooldown on several of your core abilities.' },
        { t: 4, name: 'Hemorrhage', max: 1, d: 'A strike that causes the target to bleed, increasing further damage taken.' },
        { t: 5, name: 'Quietus', max: 5, d: 'Increases the critical strike chance of your finishing moves.' },
        { t: 5, name: 'Cutthroat', max: 5, d: 'Increases the damage of your Sinister Strike and Backstab.' },
        { t: 6, name: 'Thousand Cuts', max: 1, d: 'Your finishing moves have a chance to grant an extra combo point back.' },
      ] },
    ],
  },
  priest: {
    trees: [
      { key: 'disc', name: 'Discipline', icon: 'warding-cross', talents: [
        { t: 0, name: 'Power in Light', max: 5, d: 'Your Smite and Penance deal bonus damage to targets afflicted by your Holy Fire.' },
        { t: 0, name: 'Wand Specialization', max: 2, d: 'Increases your damage with Wand per rank.' },
        { t: 0, name: 'Twin Disciplines', max: 5, d: 'Increases the damage and healing of your instant cast spells.' },
        { t: 1, name: 'Silent Resolve', max: 3, d: 'Reduces threat from your Holy spells and the duration of control effects on you.' },
        { t: 1, name: 'Holy Precision', max: 3, d: 'Improves your chance to hit with Holy spells.' },
        { t: 1, name: 'Improved Power Word: Shield', max: 3, d: 'Strengthens the effect of Power Word: Shield.' },
        { t: 1, name: 'Martyrdom', max: 2, d: 'Being struck in combat has a chance to speed up your next cast.' },
        { t: 2, name: 'Mental Agility', max: 3, d: 'Reduces the mana cost of your instant cast spells.' },
        { t: 2, name: 'Inner Focus', max: 1, d: 'Your next spell costs no mana and has a greater effect.' },
        { t: 2, name: 'Meditation', max: 3, d: 'Allows a portion of your mana regeneration to continue while casting.' },
        { t: 3, name: 'Improved Inner Fire', max: 3, d: 'Strengthens the effect of Inner Fire.' },
        { t: 3, name: 'Mental Strength', max: 5, d: 'Increases your maximum mana.' },
        { t: 3, name: 'Soul Warding', max: 1, d: 'Reduces the cooldown of Power Word: Shield.' },
        { t: 3, name: 'Improved Mana Burn', max: 2, d: 'Strengthens the effect of Mana Burn.' },
        { t: 4, name: 'Penance', max: 1, d: 'A channeled bolt of holy energy that heals an ally or damages an enemy in three quick volleys.' },
        { t: 4, name: 'Renewed Hope', max: 5, d: 'Your shield and heal effects grant the target a damage reduction buff.' },
        { t: 5, name: 'Divine Aegis', max: 3, d: 'Your critical heals also grant the target a protective shield.' },
        { t: 6, name: 'Power Infusion', max: 1, d: 'Temporarily increases the target\'s casting speed and reduces spell costs.' },
      ] },
      { key: 'holy', name: 'Holy', icon: 'sunburst', talents: [
        { t: 0, name: 'Twilight Focus', max: 3, d: 'Increases your resistance to Shadow and Holy spells.' },
        { t: 0, name: 'Improved Renew', max: 3, d: 'Strengthens the effect of Renew.' },
        { t: 0, name: 'Holy Specialization', max: 5, d: 'Increases your damage with Holy per rank.' },
        { t: 1, name: 'Spell Warding', max: 5, d: 'Reduces damage taken from spells.' },
        { t: 1, name: 'Divine Fury', max: 5, d: 'Reduces the cast time of Smite and Holy Fire.' },
        { t: 2, name: 'Holy Nova', max: 1, d: 'An instant burst of holy energy that heals nearby allies and damages nearby enemies.' },
        { t: 2, name: 'Blessed Recovery', max: 3, d: 'After being critically hit, you heal over the next few seconds.' },
        { t: 2, name: 'Inspiration', max: 3, d: 'Your critical heals grant the target bonus armor for a short time.' },
        { t: 3, name: 'Holy Reach', max: 2, d: 'Increases the radius of your party-wide spells.' },
        { t: 3, name: 'Improved Healing', max: 3, d: 'Strengthens the effect of Healing.' },
        { t: 3, name: 'Improved Searing Light', max: 2, d: 'Strengthens the effect of Searing Light.' },
        { t: 3, name: 'Binding Heal', max: 1, d: 'Heals the target and yourself simultaneously with a single cast.' },
        { t: 4, name: 'Litany of Light', max: 2, d: 'Increases the healing done by your Holy spells.' },
        { t: 4, name: 'Spirit of Redemption', max: 1, d: 'Upon death, linger as a spirit for a short time, able to continue healing.' },
        { t: 4, name: 'Spiritual Guidance', max: 5, d: 'A portion of your Spirit is added to your spell damage and healing.' },
        { t: 5, name: 'Spiritual Healing', max: 3, d: 'Increases the healing done by all your spells.' },
        { t: 6, name: 'Prayer of Mending', max: 1, d: 'An instant heal that jumps to a new injured ally each time it heals.' },
      ] },
      { key: 'shadow', name: 'Shadow Magic', icon: 'crescent-eye', talents: [
        { t: 0, name: 'Shadow Focus', max: 5, d: 'Reduces the mana cost of your Shadow spells.' },
        { t: 0, name: 'Blackout', max: 5, d: 'Your Shadow spells have a chance to stun the target.' },
        { t: 0, name: 'Spirit Tap', max: 5, d: 'Killing a target grants bonus mana regeneration for a short time.' },
        { t: 1, name: 'Shadow Affinity', max: 3, d: 'Reduces the threat generated by your Shadow spells.' },
        { t: 1, name: 'Improved Shadow Word: Pain', max: 2, d: 'Strengthens the effect of Shadow Word: Pain.' },
        { t: 1, name: 'Shadow Reach', max: 2, d: 'Increases the range of your Shadow spells.' },
        { t: 2, name: 'Improved Mind Blast', max: 5, d: 'Strengthens the effect of Mind Blast.' },
        { t: 2, name: 'Improved Psychic Scream', max: 2, d: 'Strengthens the effect of Psychic Scream.' },
        { t: 2, name: 'Mind Flay', max: 1, d: 'A channeled bolt of shadow energy that damages the target over time.' },
        { t: 2, name: 'Improved Mind Flay', max: 2, d: 'Strengthens the effect of Mind Flay.' },
        { t: 3, name: 'Improved Fade', max: 2, d: 'Strengthens the effect of Fade.' },
        { t: 3, name: 'Vampiric Embrace', max: 1, d: 'A portion of your shadow damage done also heals your party.' },
        { t: 3, name: 'Shadow Weaving', max: 3, d: 'Your Shadow spell hits stack a debuff that increases further shadow damage taken.' },
        { t: 4, name: 'Silence', max: 1, d: 'Silences the target, preventing spellcasting for a few seconds.' },
        { t: 4, name: 'Devouring Contagion', max: 2, d: 'Your Shadow Word: Pain and Vampiric Touch deal increased damage.' },
        { t: 5, name: 'Early Demise', max: 2, d: 'Increases the damage of your damage-over-time spells against low health targets.' },
        { t: 5, name: 'Darkness', max: 5, d: 'Increases your spell casting speed.' },
        { t: 6, name: 'Shadowform', max: 1, d: 'Assume a shadowy form, boosting shadow damage and reducing damage taken.' },
      ] },
    ],
  },
  shaman: {
    trees: [
      { key: 'ele', name: 'Elemental Combat', icon: 'lightning', talents: [
        { t: 0, name: 'Convection', max: 5, d: 'Reduces the mana cost of your Shock and totem spells.' },
        { t: 0, name: 'Concussion', max: 5, d: 'Increases the damage done by your Shock spells.' },
        { t: 1, name: 'Elemental Warding', max: 3, d: 'Increases your resistance to Fire, Frost and Nature spells.' },
        { t: 1, name: 'Reverberation', max: 5, d: 'Reduces the cooldown of your Shock spells.' },
        { t: 1, name: 'Call of Flame', max: 3, d: 'Increases the damage done by your Fire totems.' },
        { t: 1, name: 'Elemental Devastation', max: 3, d: 'Your spell critical strikes grant you bonus critical strike chance.' },
        { t: 2, name: 'Elemental Focus', max: 1, d: 'After a critical spell, your next spells cost less mana.' },
        { t: 2, name: 'Elemental Alacrity', max: 3, d: 'Increases your spell haste.' },
        { t: 3, name: 'Improved Fire Nova', max: 2, d: 'Strengthens the effect of Fire Nova.' },
        { t: 3, name: 'Eye of the Storm', max: 3, d: 'Gives you a chance to not be interrupted when taking damage while casting.' },
        { t: 3, name: 'Call of Thunder', max: 1, d: 'Your Lightning Bolt and Chain Lightning have a chance to grant bonus critical strike chance.' },
        { t: 4, name: 'Elemental Reach', max: 2, d: 'Increases the range of your spells and totems.' },
        { t: 4, name: 'Lightning Overload', max: 3, d: 'Your Lightning spells have a chance to strike a second time for reduced damage.' },
        { t: 4, name: 'Earthbound', max: 1, d: 'Your Earth Shock has a chance to root the target in place.' },
        { t: 5, name: 'Elemental Fury', max: 5, d: 'Increases the critical strike damage of your elemental spells.' },
        { t: 6, name: 'Lava Burst', max: 1, d: 'A bolt of lava guaranteed to critically strike any target affected by your Flame Shock.' },
      ] },
      { key: 'enh', name: 'Enhancement', icon: 'fist-spark', talents: [
        { t: 0, name: 'Earth\'s Grasp', max: 2, d: 'Your Earthbind Totem roots enemies in place occasionally.' },
        { t: 0, name: 'Thundering Strikes', max: 5, d: 'Increases your critical strike chance.' },
        { t: 0, name: 'Ancestral Knowledge', max: 5, d: 'Increases your maximum mana.' },
        { t: 1, name: 'Guardian Totems', max: 2, d: 'Increases the effect of your Stoneskin and Stoneclaw totems.' },
        { t: 1, name: 'Mental Dexterity', max: 3, d: 'A portion of your attack power is added to your healing.' },
        { t: 1, name: 'Improved Ghost Wolf', max: 2, d: 'Strengthens the effect of Ghost Wolf.' },
        { t: 1, name: 'Improved Lightning Shield', max: 3, d: 'Strengthens the effect of Lightning Shield.' },
        { t: 2, name: 'Elemental Weapons', max: 3, d: 'Improves your effectiveness with elemental weapons per rank.' },
        { t: 2, name: 'Shamanistic Focus', max: 1, d: 'Reduces the mana cost of your next shock spell after a melee critical strike.' },
        { t: 2, name: 'Anticipation', max: 3, d: 'Increases your chance to dodge.' },
        { t: 3, name: 'Toughness', max: 5, d: 'Increases your armor value from items.' },
        { t: 3, name: 'Flurry', max: 5, d: 'After a critical strike, your attack speed increases for your next few swings.' },
        { t: 3, name: 'Stormstrike', max: 1, d: 'A melee strike that also boosts your next two Nature spell hits against the target.' },
        { t: 4, name: 'Spirit Weapons', max: 1, d: 'Your melee attacks no longer generate threat, but your attack speed decreases.' },
        { t: 4, name: 'Mental Quickness', max: 2, d: 'A portion of your attack power is added to your spell damage.' },
        { t: 4, name: 'Improved Stormstrike', max: 2, d: 'Strengthens the effect of Stormstrike.' },
        { t: 5, name: 'Maelstrom Weapon', max: 5, d: 'Your melee attacks have a chance to make your next spell instant.' },
        { t: 6, name: 'Rage of the Farseer', max: 1, d: 'Your melee critical strikes have a chance to empower your next Nature spell.' },
      ] },
      { key: 'resto', name: 'Restoration', icon: 'droplet', talents: [
        { t: 0, name: 'Improved Healing Wave', max: 5, d: 'Strengthens the effect of Healing Wave.' },
        { t: 0, name: 'Totemic Focus', max: 5, d: 'Reduces the mana cost of your totem spells.' },
        { t: 1, name: 'Mindfulness', max: 3, d: 'Reduces the mana cost of your Chain Heal and Healing Wave.' },
        { t: 1, name: 'Natural Grace', max: 3, d: 'Increases your chance to hit with spells and attacks.' },
        { t: 1, name: 'Tidal Focus', max: 5, d: 'Reduces the mana cost of your healing spells.' },
        { t: 1, name: 'Improved Reincarnation', max: 2, d: 'Strengthens the effect of Reincarnation.' },
        { t: 2, name: 'Ancestral Healing', max: 3, d: 'Your healing spells also grant the target a brief shield.' },
        { t: 2, name: 'Healing Focus', max: 3, d: 'Gives you a chance to not be interrupted while healing.' },
        { t: 2, name: 'Water Shield', max: 1, d: 'Surrounds you with water globes that restore mana when you are hit.' },
        { t: 3, name: 'Tidal Mastery', max: 5, d: 'Increases the critical strike chance of your healing spells.' },
        { t: 3, name: 'Restorative Totems', max: 5, d: 'Increases the effect of your healing totems.' },
        { t: 3, name: 'Mana Tide Totem', max: 1, d: 'A totem that greatly boosts party mana regeneration for a short time.' },
        { t: 4, name: 'Healing Way', max: 3, d: 'Your healing spells have a chance to reduce the cost of your next heal.' },
        { t: 4, name: 'Nature\'s Swiftness', max: 1, d: 'Your next Nature spell is cast instantly.' },
        { t: 5, name: 'Purification', max: 5, d: 'Increases the healing done by your spells.' },
        { t: 6, name: 'Riptide', max: 1, d: 'An instant heal that also leaves a heal-over-time on the target.' },
      ] },
    ],
  },
  mage: {
    trees: [
      { key: 'arcane', name: 'Arcane', icon: 'star-burst', talents: [
        { t: 0, name: 'Wand Specialization', max: 2, d: 'Increases your damage with Wand per rank.' },
        { t: 0, name: 'Arcane Focus', max: 5, d: 'Reduces the mana cost of your Arcane spells.' },
        { t: 0, name: 'Improved Channeling', max: 5, d: 'Strengthens the effect of Channeling.' },
        { t: 1, name: 'Arcane Subtlety', max: 2, d: 'Reduces the threat generated by your Arcane spells.' },
        { t: 1, name: 'Magic Absorption', max: 2, d: 'Increases your resistance to all magic schools.' },
        { t: 1, name: 'Arcane Concentration', max: 5, d: 'Critical spell hits have a chance to make your next spell instant.' },
        { t: 1, name: 'Arcane Resilience', max: 2, d: 'Increases your resistance related to arcane resilience.' },
        { t: 2, name: 'Arcane Geometry', max: 2, d: 'Increases the critical strike chance of your Arcane spells.' },
        { t: 2, name: 'Arcane Impact', max: 3, d: 'Increases the critical strike damage of your Arcane spells.' },
        { t: 2, name: 'Arcane Blast', max: 1, d: 'A powerful arcane bolt that grows stronger the more you cast it in succession.' },
        { t: 3, name: 'Arcane Shielding', max: 2, d: 'Reduces damage taken while your Mana Shield is active.' },
        { t: 3, name: 'Improved Counterspell', max: 2, d: 'Strengthens the effect of Counterspell.' },
        { t: 3, name: 'Arcane Meditation', max: 3, d: 'Allows a portion of your mana regeneration to continue while casting.' },
        { t: 3, name: 'Missile Barrage', max: 1, d: 'Your damaging spells have a chance to make your next Arcane Missiles instant.' },
        { t: 4, name: 'Presence of Mind', max: 1, d: 'Your next spell is cast instantly.' },
        { t: 4, name: 'Arcane Mind', max: 5, d: 'Increases your maximum mana.' },
        { t: 5, name: 'Arcane Instability', max: 3, d: 'Increases your spell critical strike and damage.' },
        { t: 6, name: 'Arcane Power', max: 1, d: 'Temporarily increases spell damage, at the cost of increased mana costs.' },
      ] },
      { key: 'fire', name: 'Fire', icon: 'flame', talents: [
        { t: 0, name: 'Wake of Fire', max: 2, d: 'Increases the radius of your fire spells\' knockback and stun effects.' },
        { t: 0, name: 'Incineration', max: 3, d: 'Increases the critical strike chance of your Fire spells.' },
        { t: 0, name: 'Improved Fireball', max: 5, d: 'Strengthens the effect of Fireball.' },
        { t: 1, name: 'Ignite', max: 5, d: 'Critical fire hits leave a burning DoT on the target.' },
        { t: 1, name: 'Flame Throwing', max: 2, d: 'Increases the range of your fire spells.' },
        { t: 1, name: 'Impact', max: 3, d: 'Your fire spells have a chance to stun the target.' },
        { t: 2, name: 'Burning Soul', max: 3, d: 'Reduces the threat generated by your fire spells.' },
        { t: 2, name: 'Improved Flamestrike', max: 3, d: 'Strengthens the effect of Flamestrike.' },
        { t: 2, name: 'Pyroblast', max: 1, d: 'A very powerful, slow-casting fire spell.' },
        { t: 3, name: 'Improved Scorch', max: 3, d: 'Strengthens the effect of Scorch.' },
        { t: 3, name: 'Improved Fire Ward', max: 2, d: 'Strengthens the effect of Fire Ward.' },
        { t: 3, name: 'Heating Up', max: 1, d: 'Fire spell critical strikes stack a buff that empowers your next Pyroblast.' },
        { t: 3, name: 'Master of Elements', max: 3, d: 'Your critical spell hits refund a portion of their mana cost.' },
        { t: 4, name: 'Critical Mass', max: 3, d: 'Increases the critical strike chance of your fire spells.' },
        { t: 4, name: 'Blast Wave', max: 1, d: 'A fiery explosion that damages and disorients all nearby enemies.' },
        { t: 5, name: 'Fire Power', max: 5, d: 'Increases your fire spell damage.' },
        { t: 6, name: 'Combustion', max: 1, d: 'Your next few spells are guaranteed to critically strike.' },
      ] },
      { key: 'frost', name: 'Frost', icon: 'snowflake', talents: [
        { t: 0, name: 'Frost Warding', max: 2, d: 'Increases your resistance to Frost spells.' },
        { t: 0, name: 'Improved Frostbolt', max: 5, d: 'Strengthens the effect of Frostbolt.' },
        { t: 0, name: 'Elemental Precision', max: 5, d: 'Improves your chance to hit with Fire, Frost and Nature spells.' },
        { t: 1, name: 'Ice Shards', max: 5, d: 'Increases the critical strike damage of your frost spells.' },
        { t: 1, name: 'Permafrost', max: 3, d: 'Frozen targets remain slowed for longer after thawing.' },
        { t: 1, name: 'Improved Frost Nova', max: 2, d: 'Strengthens the effect of Frost Nova.' },
        { t: 1, name: 'Frostbite', max: 3, d: 'Your frost spells have a chance to freeze the target in place.' },
        { t: 2, name: 'Piercing Ice', max: 3, d: 'Increases the damage done by your frost spells.' },
        { t: 2, name: 'Frost Channeling', max: 3, d: 'Reduces the mana cost of your frost spells.' },
        { t: 2, name: 'Ice Lance', max: 1, d: 'An instant frost bolt that deals bonus damage to frozen targets.' },
        { t: 2, name: 'Improved Blizzard', max: 3, d: 'Strengthens the effect of Blizzard.' },
        { t: 3, name: 'Arctic Reach', max: 2, d: 'Increases the range of your frost spells.' },
        { t: 3, name: 'Ice Block', max: 1, d: 'Encases you in ice, making you immune to all damage and spells for a short time.' },
        { t: 3, name: 'Shatter', max: 3, d: 'Increases the critical strike chance of spells against frozen targets.' },
        { t: 4, name: 'Improved Cone of Cold', max: 3, d: 'Strengthens the effect of Cone of Cold.' },
        { t: 4, name: 'Cold Snap', max: 1, d: 'Instantly resets the cooldown on several of your Frost spells.' },
        { t: 4, name: 'Fingers of Frost', max: 2, d: 'Your frost spells have a chance to guarantee your next spell crits.' },
        { t: 5, name: 'Winter\'s Chill', max: 5, d: 'Your frost spells reduce the target\'s resistance to further frost damage.' },
        { t: 6, name: 'Ice Barrier', max: 1, d: 'A shield that absorbs damage for a short time.' },
      ] },
    ],
  },
  warlock: {
    trees: [
      { key: 'affl', name: 'Affliction', icon: 'skull-wisp', talents: [
        { t: 0, name: 'Improved Life Tap', max: 2, d: 'Strengthens the effect of Life Tap.' },
        { t: 0, name: 'Suppression', max: 5, d: 'Improves your chance to hit with Affliction spells.' },
        { t: 0, name: 'Improved Corruption', max: 5, d: 'Strengthens the effect of Corruption.' },
        { t: 1, name: 'Malediction', max: 5, d: 'Increases the damage done by your curses.' },
        { t: 1, name: 'Soul Harvest', max: 2, d: 'Killing a target has a chance to restore health and mana.' },
        { t: 1, name: 'Improved Drains', max: 3, d: 'Strengthens the effect of Drains.' },
        { t: 2, name: 'Improved Bane of Agony', max: 2, d: 'Strengthens the effect of Bane of Agony.' },
        { t: 2, name: 'Fel Concentration', max: 3, d: 'Gives you a chance to not be interrupted while channeling drain effects.' },
        { t: 2, name: 'Amplify Curse', max: 1, d: 'Increases the effect of your next curse cast.' },
        { t: 2, name: 'Pandemic', max: 3, d: 'Refreshing a damage-over-time effect can trigger a burst of damage.' },
        { t: 3, name: 'Malevolence', max: 5, d: 'Increases the damage of your damage-over-time spells.' },
        { t: 3, name: 'Nightfall', max: 2, d: 'Your Corruption and Drain Life have a chance to grant a free instant Shadow Bolt.' },
        { t: 3, name: 'Curse of Exhaustion', max: 1, d: 'A curse that slows the target\'s movement speed.' },
        { t: 4, name: 'Siphon Life', max: 1, d: 'A DoT that heals you for a portion of the damage it deals.' },
        { t: 4, name: 'Soul Siphon', max: 3, d: 'Your drain spells are more effective against targets you have afflicted with DoTs.' },
        { t: 5, name: 'Shadow Mastery', max: 5, d: 'Increases your shadow spell damage.' },
        { t: 6, name: 'Wrack', max: 1, d: 'A shadow bolt that boosts the damage of your DoTs on the target and returns health when it dies.' },
      ] },
      { key: 'demo', name: 'Demonology', icon: 'demon-horns', talents: [
        { t: 0, name: 'Improved Health Funnel', max: 2, d: 'Strengthens the effect of Health Funnel.' },
        { t: 0, name: 'Improved Imp', max: 3, d: 'Strengthens the effect of Imp.' },
        { t: 0, name: 'Demonic Embrace', max: 5, d: 'Increases your maximum health, at the cost of maximum mana.' },
        { t: 0, name: 'Unholy Power', max: 5, d: 'Increases your summoned demon\'s damage done.' },
        { t: 1, name: 'Demonic Aegis', max: 2, d: 'Increases the effect of your demon\'s defensive abilities.' },
        { t: 1, name: 'Improved Voidwalker', max: 3, d: 'Strengthens the effect of Voidwalker.' },
        { t: 1, name: 'Fel Vitality', max: 3, d: 'Increases your and your demon\'s maximum health and mana.' },
        { t: 1, name: 'Demonic Energies', max: 2, d: 'Increases your maximum mana and your demon\'s maximum mana.' },
        { t: 2, name: 'Improved Sayaad', max: 3, d: 'Strengthens the effect of Sayaad.' },
        { t: 2, name: 'Demonic Sacrifice', max: 1, d: 'Sacrifice your summoned demon for a lasting personal bonus.' },
        { t: 2, name: 'Master Summoner', max: 2, d: 'Reduces the cast time and mana cost of demon summoning spells.' },
        { t: 3, name: 'Decimation', max: 2, d: 'Your Shadow Bolt and Incinerate cast faster against low health targets.' },
        { t: 3, name: 'Fel Domination', max: 1, d: 'Your next demon summon is instant.' },
        { t: 3, name: 'Demonic Brand', max: 3, d: 'Your demon\'s attacks mark the target, increasing damage it takes from you.' },
        { t: 4, name: 'Improved Felhunter', max: 3, d: 'Strengthens the effect of Felhunter.' },
        { t: 4, name: 'Soul Link', max: 1, d: 'Shares a portion of damage you take with your summoned demon.' },
        { t: 4, name: 'Demonic Knowledge', max: 3, d: 'A portion of your demon\'s stats are added to your spell damage.' },
        { t: 5, name: 'Master Demonologist', max: 5, d: 'Grants a bonus based on which demon you currently have summoned.' },
        { t: 6, name: 'Demonic Pact', max: 1, d: 'Your summoned demon\'s presence grants spell damage to your entire party.' },
      ] },
      { key: 'destro', name: 'Destruction', icon: 'fireball', talents: [
        { t: 0, name: 'Destructive Reach', max: 2, d: 'Increases the range of your Destruction spells.' },
        { t: 0, name: 'Improved Shadow Bolt', max: 5, d: 'Strengthens the effect of Shadow Bolt.' },
        { t: 0, name: 'Bane', max: 5, d: 'Reduces the cast time of your Destruction spells.' },
        { t: 1, name: 'Molten Skin', max: 5, d: 'Reduces damage taken from Fire spells.' },
        { t: 1, name: 'Cataclysm', max: 3, d: 'Reduces the mana cost of your Destruction spells.' },
        { t: 1, name: 'Aftermath', max: 5, d: 'Your Destruction spells have a chance to slow the target.' },
        { t: 2, name: 'Ruin', max: 5, d: 'Increases the critical strike damage of your Destruction spells.' },
        { t: 2, name: 'Shadowburn', max: 1, d: 'An instant spell that refunds a soul shard if it kills the target.' },
        { t: 3, name: 'Intensity', max: 3, d: 'Gives you a chance to not be interrupted when taking damage while casting.' },
        { t: 3, name: 'Agonizing Flames', max: 3, d: 'Increases the duration of your Immolate and Corruption.' },
        { t: 3, name: 'Conflagrate', max: 1, d: 'Detonates your Immolate on the target for a burst of fire damage.' },
        { t: 4, name: 'Pyroclasm', max: 2, d: 'After a stun, your critical strike chance is increased for a few seconds.' },
        { t: 4, name: 'Bane of Havoc', max: 1, d: 'A curse that causes damage dealt to the target to also strike a second enemy.' },
        { t: 4, name: 'Fire and Brimstone', max: 3, d: 'Increases the critical strike chance of your Destruction spells.' },
        { t: 5, name: 'Shadow and Flame', max: 5, d: 'Increases your Shadow and Fire spell damage.' },
        { t: 6, name: 'Incinerate', max: 1, d: 'A fast-casting fire bolt empowered by your Immolate on the target.' },
      ] },
    ],
  },
  druid: {
    trees: [
      { key: 'balance', name: 'Balance', icon: 'moon-sun', talents: [
        { t: 0, name: 'Improved Wrath', max: 5, d: 'Strengthens the effect of Wrath.' },
        { t: 0, name: 'Genesis', max: 5, d: 'Increases the damage done by your Starfire and Wrath.' },
        { t: 1, name: 'Moonglow', max: 3, d: 'Reduces the mana cost of your main healing and nuking spells.' },
        { t: 1, name: 'Improved Moonfire', max: 2, d: 'Strengthens the effect of Moonfire.' },
        { t: 1, name: 'Nature\'s Majesty', max: 2, d: 'Increases the critical strike chance of your spells.' },
        { t: 1, name: 'Nature\'s Reach', max: 2, d: 'Increases the range of your spells.' },
        { t: 2, name: 'Improved Entangling Roots', max: 3, d: 'Strengthens the effect of Entangling Roots.' },
        { t: 2, name: 'Nature\'s Splendor', max: 1, d: 'Reduces the cooldown of your Entangling Roots.' },
        { t: 3, name: 'Insect Swarm', max: 1, d: 'A DoT that reduces the target\'s chance to hit you.' },
        { t: 3, name: 'Vengeance', max: 5, d: 'Increases the critical strike damage of your Arcane and Nature spells.' },
        { t: 3, name: 'Improved Starfire', max: 5, d: 'Strengthens the effect of Starfire.' },
        { t: 4, name: 'Overgrowth', max: 2, d: 'Increases the duration of your Moonfire and Insect Swarm.' },
        { t: 4, name: 'Nature\'s Grace', max: 1, d: 'After a critical spell, your next cast is faster.' },
        { t: 4, name: 'Eclipse', max: 3, d: 'Your Wrath and Starfire casts have a chance to empower your next spell.' },
        { t: 5, name: 'Moonfury', max: 5, d: 'Increases your Arcane and Nature spell damage.' },
        { t: 6, name: 'Moonkin Form', max: 1, d: 'Shapeshift into a Moonkin, boosting spell damage and granting an aura to the party.' },
      ] },
      { key: 'feral', name: 'Feral Combat', icon: 'claw', talents: [
        { t: 0, name: 'Ferocity', max: 5, d: 'Reduces the rage or energy cost of several of your feral abilities.' },
        { t: 0, name: 'Heart of the Wild', max: 5, d: 'Increases your Intellect, and grants bonuses while shapeshifted.' },
        { t: 1, name: 'Feral Swiftness', max: 2, d: 'Increases your movement speed while in Cat Form.' },
        { t: 1, name: 'Feral Instinct', max: 3, d: 'Increases threat generated in Bear Form and dodge chance in Cat Form.' },
        { t: 1, name: 'Brutal Impact', max: 2, d: 'Increases the stun duration of your Bash and Pounce.' },
        { t: 1, name: 'Thick Hide', max: 3, d: 'Increases your armor value while in Bear Form.' },
        { t: 2, name: 'Shredding Attacks', max: 3, d: 'Increases the damage done by Shred and Maul.' },
        { t: 2, name: 'Savage Fury', max: 2, d: 'Increases the damage done by Claw and Mangle.' },
        { t: 2, name: 'Feral Charge', max: 1, d: 'Charges an enemy and stuns it on impact, usable in Bear or Cat Form.' },
        { t: 2, name: 'Sharpened Claws', max: 2, d: 'Increases your critical strike chance in Bear and Cat Form.' },
        { t: 3, name: 'Shifting Power', max: 1, d: 'Reduces the cooldown on your shapeshift forms.' },
        { t: 3, name: 'Primal Bite', max: 1, d: 'Your finishing moves have a chance to refund the energy spent.' },
        { t: 3, name: 'Predatory Strikes', max: 3, d: 'Increases your attack power based on your level while shapeshifted.' },
        { t: 3, name: 'Blood Frenzy', max: 2, d: 'Increases physical damage taken by targets you have bled.' },
        { t: 4, name: 'Improved Shifting Power', max: 2, d: 'Strengthens the effect of Shifting Power.' },
        { t: 4, name: 'Leader of the Pack', max: 1, d: 'While shapeshifted, grants a critical strike chance bonus to your party.' },
        { t: 4, name: 'Predatory Instincts', max: 2, d: 'Increases the damage of your finishing moves in Cat Form.' },
        { t: 5, name: 'Natural Reaction', max: 5, d: 'Increases your dodge chance while in Bear Form.' },
        { t: 5, name: 'Rend and Tear', max: 5, d: 'Increases the critical strike chance of your bleed-consuming finishers.' },
        { t: 6, name: 'Berserk', max: 1, d: 'Removes the cooldown on several of your core feral abilities for a short time.' },
      ] },
      { key: 'resto', name: 'Restoration', icon: 'droplet', talents: [
        { t: 0, name: 'Nature\'s Focus', max: 5, d: 'Gives you a chance to not be interrupted while healing.' },
        { t: 0, name: 'Furor', max: 5, d: 'Gives you a chance to gain energy or rage when you shapeshift.' },
        { t: 1, name: 'Naturalist', max: 5, d: 'Reduces the cast time of Healing Touch.' },
        { t: 1, name: 'Subtlety', max: 3, d: 'Reduces the threat generated by your healing spells.' },
        { t: 1, name: 'Natural Shapeshifter', max: 3, d: 'Reduces the mana cost of shapeshifting.' },
        { t: 2, name: 'Reflection', max: 3, d: 'Increases your spell critical strike chance.' },
        { t: 2, name: 'Gift of Nature', max: 5, d: 'Increases the healing done by all your spells.' },
        { t: 2, name: 'Gift of the Earthmother', max: 1, d: 'Reduces the cooldown of Rebirth and its reagent cost.' },
        { t: 3, name: 'Tranquil Spirit', max: 5, d: 'Reduces the mana cost of Healing Touch and Tranquility.' },
        { t: 3, name: 'Improved Rejuvenation', max: 3, d: 'Strengthens the effect of Rejuvenation.' },
        { t: 3, name: 'Swiftmend', max: 1, d: 'An instant heal that consumes a Rejuvenation or Regrowth on the target.' },
        { t: 4, name: 'Nature\'s Swiftness', max: 1, d: 'Your next Nature spell is cast instantly.' },
        { t: 4, name: 'Living Spirit', max: 3, d: 'Increases your Spirit.' },
        { t: 4, name: 'Improved Tranquility', max: 2, d: 'Strengthens the effect of Tranquility.' },
        { t: 5, name: 'Improved Regrowth', max: 5, d: 'Strengthens the effect of Regrowth.' },
        { t: 6, name: 'Wild Growth', max: 1, d: 'An instant heal-over-time that lands on several injured allies near the target at once.' },
      ] },
    ],
  },
};


// Real, sourced Forever-specific changes — read from wowforever.sk's own news posts and class
// beta-overview pages (not invented talent nodes). Coverage varies: some classes have detailed
// deep-dive articles, others only a short beta-overview page, which is noted per entry.
export const FOREVER_CHANGES = {
  general: {
    label: 'Systém talentov',
    source: 'Beta poznámky, strop postavy 30',
    points: [
      'Talenty sa otvárajú na leveli 10, rovnako ako vo vanille.',
      'Pribudli nové medzníky pri 11, 21 a 31 minutých bodoch — menšie bonusy medzi klasickými prahmi po každých 5 bodoch.',
      'Na 16 bodoch je nová voliteľná vetva (napr. u druida voľba medzi Primal Bite a Shifting Power) — Forever tu dáva hráčovi reálnu voľbu namiesto jedného povinného talentu.',
      'Respec talentov je stále len cez trénera danej triedy.',
      'Dual Specialization (druhá sada talentov) sa odomyká na leveli 40.',
    ],
  },
  warrior: {
    label: 'Warrior',
    source: 'Class deep-dive článok',
    points: [
      'Upravený vzorec generovania rage — warrior naberá rage inak než vo vanille (presné čísla sa počas bety ešte ladia).',
      'Tactical Mastery funguje už od levelu 14.',
      'Victory Rush je k dispozícii od levelu 20.',
      'Kritický zásah dáva až 100% bonus rage namiesto klasického nižšieho pomeru.',
    ],
  },
  paladin: {
    label: 'Paladin',
    source: 'Class beta-overview (čiastkové info)',
    points: [
      'Judgement už nespotrebuje aktívny seal — seal ostáva aktívny aj po Judgemente, takže ho netreba stále dokola obnovovať.',
      'Holy Strike rozširuje základný melee kit paladina (presné čísla stránka neuvádza).',
    ],
  },
  hunter: {
    label: 'Hunter',
    source: 'Class deep-dive článok',
    points: [
      'Aimed Shot je dostupný už od levelu 20 ako základná schopnosť.',
      'Arcane Shot a Multi-Shot zdieľajú cooldown.',
      'Pasce sa dajú klásť priamo v boji (combat-placeable), nie len mimo neho.',
      'Pribudla nová rodina spoločníkov — líška (Fox pet family).',
    ],
  },
  rogue: {
    label: 'Rogue',
    source: 'Class beta-overview (čiastkové info)',
    points: [
      'Regenerácia energie je plynulá, nie na klasických oddelených tikoch.',
      'Poškodenie jedov škáluje s Attack Power.',
    ],
  },
  priest: {
    label: 'Priest',
    source: 'Class deep-dive článok',
    points: [
      'Fear Ward a Devouring Plague sú dostupné všetkým priestom od levelu 20, bez ohľadu na špecializáciu.',
      'Rasové schopnosti priesta boli prerobené oproti vanille.',
    ],
  },
  shaman: {
    label: 'Shaman',
    source: 'Class beta-overview (čiastkové info)',
    points: [
      'Totemic Recall zruší aktívne totemy a vráti časť ich many.',
      'Totemic Projection presunie existujúce totemy na nové miesto bez nutnosti ich znova postaviť.',
    ],
  },
  mage: {
    label: 'Mage',
    source: 'Class beta-overview (čiastkové info)',
    points: [
      'Nový systém „Comprehend Scroll" dáva mágom situačné scroll-kúzla popri klasickej rotácii.',
      'Podľa októbrových beta poznámok prebieha ďalší balance pass a scroll-kúzla nejde castovať počas pohybu.',
    ],
  },
  warlock: {
    label: 'Warlock',
    source: 'Class beta-overview (čiastkové info)',
    points: [
      'Banes a utility Curses sú oddelené — Bane of Agony tak môže bežať súčasne s Curse of the Elements na tom istom cieli.',
      'Life Tap funguje ako vo vanille, bez uvedených zmien.',
    ],
  },
  druid: {
    label: 'Druid',
    source: 'Class deep-dive článok',
    points: [
      'Shapeshifting už nebráni použitiu potiónov a iných konzumovateľných predmetov.',
      'Revive (oživenie spoluhráča) je dostupné od levelu 12.',
      'Na 16 bodoch vo Ferale je nová voľba medzi Primal Bite a Shifting Power (plus Improved Shifting Power).',
    ],
  },
};

// Walks each tree in order and spends points top-down, maxing each talent before moving on —
// generates the recommended builds and their shareable calculator link.
export function greedyAllocate(classSlug, order, budget = 51) {
  const trees = TALENT_TREES[classSlug].trees;
  const ranks = trees.map((t) => t.talents.map(() => 0));
  const spent = trees.map(() => 0);
  let remaining = budget;
  for (const ti of order) {
    const tree = trees[ti];
    const maxTier = Math.max(...tree.talents.map((t) => t.t));
    for (let tier = 0; tier <= maxTier; tier++) {
      if (spent[ti] < tier * 5) break;
      tree.talents.forEach((tal, idx) => {
        if (tal.t !== tier || remaining <= 0) return;
        const add = Math.min(tal.max, remaining);
        ranks[ti][idx] = add;
        spent[ti] += add;
        remaining -= add;
      });
    }
  }
  const hash = ranks.map((r) => r.join('')).join('-');
  const picks = trees.map((tree, ti) => tree.talents
    .map((tal, idx) => ({ name: tal.name, rank: ranks[ti][idx], max: tal.max }))
    .filter((p) => p.rank > 0));
  return { hash, picks, spent, totalSpent: budget - remaining };
}

// Rough builds inspired by well-known community leveling/raid specs (Wowhead Classic, Icy Veins and
// others), recomputed on our own calculator — exact point counts differ from those sources since our
// trees are a condensed, original version.
export const BUILD_PLAN = [
  { slug: 'warrior', level: { order: [1, 0, 2], label: 'Fury', note: 'Dual-wield so sústavným poškodením uľahčuje sólo levelovanie a farmenie.' }, raid: { order: [2, 0, 1], label: 'Protection', note: 'Najžiadanejšia rola warriora v raide — tank s vysokým brnením a threatom.' } },
  { slug: 'paladin', level: { order: [2, 0, 1], label: 'Retribution', note: 'Seal of Command a melee sila zrýchlia levelovanie aj sólo questing.' }, raid: { order: [0, 2, 1], label: 'Holy', note: 'Primárna raidová rola paladina — masové a spoľahlivé liečenie.' } },
  { slug: 'hunter', level: { order: [0, 2, 1], label: 'Beast Mastery', note: 'Silný a odolný pet výrazne znižuje riziko pri sólo levelovaní.' }, raid: { order: [1, 0, 2], label: 'Marksmanship', note: 'Najvyšší stabilný ranged damage na dlhé raidové fighty.' } },
  { slug: 'rogue', level: { order: [1, 0, 2], label: 'Combat', note: 'Vyššia výdrž a damage v dlhších súbojoch počas levelovania.' }, raid: { order: [0, 1, 2], label: 'Assassination', note: 'Jedy a combo body dávajú v raide stabilný a vysoký damage.' } },
  { slug: 'priest', level: { order: [2, 0, 1], label: 'Shadow', note: 'Vlastný damage a drain many uľahčia bezpečné sólo hranie.' }, raid: { order: [1, 0, 2], label: 'Holy', note: 'Primárna raidová rola priesta — hlavný liečiteľ skupiny.' } },
  { slug: 'shaman', level: { order: [1, 0, 2], label: 'Enhancement', note: 'Melee sila a Windfury pomáhajú rýchlejšie zabíjať pri levelovaní.' }, raid: { order: [2, 0, 1], label: 'Restoration', note: 'Chain Heal a totemy z neho robia kľúčového raidového healera.' } },
  { slug: 'mage', level: { order: [1, 2, 0], label: 'Fire', note: 'Vysoký burst a AoE farmenie celých packov zrýchli levelovanie.' }, raid: { order: [1, 0, 2], label: 'Fire', note: 'Štandardná raidová špecializácia mága vo vanille.' } },
  { slug: 'warlock', level: { order: [0, 1, 2], label: 'Affliction', note: 'DoT kúzla a Drain Life umožňujú bezpečné a pohodlné sólo levelovanie.' }, raid: { order: [2, 0, 1], label: 'Destruction', note: 'Shadowburn a Ruin dávajú v raide silný burst damage.' } },
  { slug: 'druid', level: { order: [1, 2, 0], label: 'Feral', note: 'Medveď na tankovanie, mačka na damage — flexibilita pri sólo hraní.' }, raid: { order: [2, 0, 1], label: 'Restoration', note: 'Primárna raidová rola druida — HoT liečenie celej skupiny.' } },
];
