// Our own talent calculator for WoW Forever — data is our condensed summary of the real
// classic talent trees (facts about the game, not text or icons taken from Blizzard).
// Each tree has 6 base tiers, unlocking every 5 points spent in that tree (0/5/10/15/20/25),
// plus one deeper tier-6 "New in Forever" capstone per tree (unlocks at 30) — a real post-vanilla
// ability folded back in, matching the site's premise that Forever reworked talents so every
// spec is viable. Format: { t: tier, name, max: maxRank, d: short effect, nf?: true for "new in Forever" }

export const TALENT_TREES = {
  warrior: {
    trees: [
      { key: 'arms', name: 'Arms', icon: 'sword', talents: [
        { t: 0, name: 'Improved Heroic Strike', max: 3, d: 'Reduces the rage cost of Heroic Strike by 1/2/3.' },
        { t: 0, name: 'Deflection', max: 5, d: '+1% parry chance per rank.' },
        { t: 1, name: 'Improved Rend', max: 3, d: 'Increases the damage done by Rend.' },
        { t: 1, name: 'Iron Will', max: 5, d: '+ chance to resist stun effects.' },
        { t: 2, name: 'Deep Wounds', max: 3, d: 'Critical strikes cause the target to bleed over 6 sec.' },
        { t: 2, name: 'Two-Handed Weapon Specialization', max: 5, d: '+1% damage per rank with two-handed weapons.' },
        { t: 3, name: 'Impale', max: 2, d: '+10/20% critical strike damage.' },
        { t: 3, name: 'Improved Overpower', max: 2, d: '+25/50% critical strike chance with Overpower.' },
        { t: 4, name: 'Weapon Mastery', max: 5, d: '+1% damage per rank with one-handed weapons.' },
        { t: 4, name: 'Tactical Mastery', max: 5, d: 'Keep more rage when switching stances.' },
        { t: 5, name: 'Mortal Strike', max: 1, d: 'A vicious strike that reduces healing received by the target for 10 sec.' },
        { t: 6, nf: true, name: 'Bladestorm', max: 1, d: 'New in Forever — spin into a whirlwind of steel, striking all nearby enemies for several seconds.' },
      ] },
      { key: 'fury', name: 'Fury', icon: 'flame-fist', talents: [
        { t: 0, name: 'Booming Voice', max: 5, d: '+ radius and duration of your shout effects.' },
        { t: 0, name: 'Cruelty', max: 5, d: '+1% critical strike chance per rank.' },
        { t: 1, name: 'Improved Demoralizing Shout', max: 5, d: 'Demoralizing Shout reduces attack power further.' },
        { t: 1, name: 'Unbridled Wrath', max: 5, d: 'Chance to generate extra rage on a successful melee attack.' },
        { t: 2, name: 'Piercing Howl', max: 1, d: 'An AoE shout that snares nearby enemies.' },
        { t: 2, name: 'Blood Craze', max: 3, d: 'After being hit, regenerate health over the next few seconds.' },
        { t: 3, name: 'Dual Wield Specialization', max: 5, d: '+1% damage per rank with your off-hand weapon.' },
        { t: 3, name: 'Improved Execute', max: 2, d: 'Execute costs less rage.' },
        { t: 4, name: 'Enrage', max: 5, d: 'Taking damage has a chance to increase your damage done for a few seconds.' },
        { t: 4, name: 'Death Wish', max: 1, d: '+20% physical damage, but also increased damage taken, for 30 sec.' },
        { t: 5, name: 'Flurry', max: 5, d: 'After a critical strike, attack speed is increased for your next few swings.' },
        { t: 6, nf: true, name: 'Raging Blow', max: 1, d: 'New in Forever — an instant strike only usable while enraged, dealing heavy extra damage.' },
      ] },
      { key: 'prot', name: 'Protection', icon: 'shield', talents: [
        { t: 0, name: 'Improved Bloodrage', max: 2, d: 'Bloodrage also heals you for a small amount.' },
        { t: 0, name: 'Toughness', max: 5, d: '+2% armor value from items per rank.' },
        { t: 1, name: 'Improved Shield Block', max: 3, d: 'Shield Block lasts longer and has a shorter cooldown.' },
        { t: 1, name: 'Anger Management', max: 1, d: 'Generate 1 rage every 3 sec automatically.' },
        { t: 2, name: 'Improved Sunder Armor', max: 3, d: 'Sunder Armor costs less rage.' },
        { t: 2, name: 'Improved Revenge', max: 3, d: 'Revenge has a chance to stun the target.' },
        { t: 3, name: 'Defiance', max: 5, d: '+ threat generated while in Defensive Stance.' },
        { t: 3, name: 'Improved Shield Wall', max: 2, d: 'Shield Wall has a shorter cooldown.' },
        { t: 4, name: 'Last Stand', max: 1, d: 'Temporarily increases maximum health by 30%.' },
        { t: 4, name: 'One-Handed Weapon Specialization', max: 5, d: '+1% damage per rank with one-handed weapons while using a shield.' },
        { t: 5, name: 'Shield Slam', max: 1, d: 'Slams the target with your shield, dealing damage based on your block value.' },
        { t: 6, nf: true, name: 'Shockwave', max: 1, d: 'New in Forever — sends a shockwave in front of you, stunning and damaging all enemies hit.' },
      ] },
    ],
  },
  paladin: {
    trees: [
      { key: 'holy', name: 'Holy', icon: 'sunburst', talents: [
        { t: 0, name: 'Spiritual Focus', max: 5, d: 'Chance not to be interrupted when casting healing spells.' },
        { t: 0, name: 'Improved Lay on Hands', max: 2, d: 'Reduces the cooldown of Lay on Hands.' },
        { t: 1, name: 'Divinity', max: 5, d: '+1% healing and damage done by your spells per rank.' },
        { t: 1, name: 'Improved Blessing of Wisdom', max: 2, d: 'Blessing of Wisdom returns more mana.' },
        { t: 2, name: 'Unyielding Faith', max: 2, d: '+ resistance to Fear and Horror effects.' },
        { t: 2, name: 'Illumination', max: 5, d: 'Critical heals refund part of their mana cost.' },
        { t: 3, name: 'Improved Holy Light', max: 3, d: 'Reduces the cast time of Holy Light.' },
        { t: 3, name: 'Holy Power', max: 5, d: '+1% critical strike chance with healing spells per rank.' },
        { t: 4, name: 'Blessed Recovery', max: 3, d: 'After being critically hit, heal yourself over 3 sec.' },
        { t: 5, name: 'Holy Shock', max: 1, d: 'An instant holy nova that heals an ally or damages an enemy.' },
        { t: 6, nf: true, name: 'Beacon of Light', max: 1, d: 'New in Forever — your heals on the target also heal a beaconed ally, sharing the load across the raid.' },
      ] },
      { key: 'prot', name: 'Protection', icon: 'shield', talents: [
        { t: 0, name: 'Redoubt', max: 5, d: 'After blocking, +chance to block for a few seconds.' },
        { t: 0, name: 'Precision', max: 3, d: '+1% chance to hit per rank.' },
        { t: 1, name: 'Toughness', max: 5, d: '+2% armor value from items per rank.' },
        { t: 1, name: 'Blessing of Kings', max: 1, d: 'A new blessing: +10% to all stats.' },
        { t: 2, name: 'Improved Righteous Fury', max: 3, d: 'Righteous Fury generates more threat.' },
        { t: 2, name: 'Improved Hammer of Justice', max: 2, d: '+ stun duration on Hammer of Justice.' },
        { t: 3, name: 'Shield Specialization', max: 5, d: '+1% chance to block per rank.' },
        { t: 3, name: 'Guardian\'s Favor', max: 2, d: '+ range and -cooldown on Hand of Freedom/Protection.' },
        { t: 4, name: 'Reckoning', max: 5, d: 'Chance for an extra melee attack when you are struck in combat.' },
        { t: 5, name: 'Holy Shield', max: 1, d: '+ block chance, and blocked attacks damage the attacker.' },
        { t: 6, nf: true, name: 'Avenger\'s Shield', max: 1, d: 'New in Forever — hurls a holy shield that damages and silences several enemies.' },
      ] },
      { key: 'ret', name: 'Retribution', icon: 'warhammer', talents: [
        { t: 0, name: 'Benediction', max: 5, d: '-1% mana cost of your spells per rank.' },
        { t: 0, name: 'Improved Blessing of Might', max: 5, d: 'Blessing of Might grants more attack power.' },
        { t: 1, name: 'Deflection', max: 5, d: '+1% parry chance per rank.' },
        { t: 1, name: 'Improved Judgement', max: 3, d: 'Reduces the cooldown of Judgement.' },
        { t: 2, name: 'Vindication', max: 3, d: 'Your attacks reduce the target\'s attack power or spell damage for a time.' },
        { t: 2, name: 'Conviction', max: 5, d: '+1% critical strike chance per rank.' },
        { t: 3, name: 'Seal of Command', max: 1, d: 'A new seal: chance for an extra attack whenever you land a hit.' },
        { t: 3, name: 'Crusade', max: 5, d: '+ damage and healing done against Humans, Orcs, Demons and Undead.' },
        { t: 4, name: 'Sanctity Aura', max: 1, d: 'An aura that increases holy damage done by the party.' },
        { t: 5, name: 'Repentance', max: 1, d: 'Puts the target in a state of stasis for a short time.' },
        { t: 6, nf: true, name: 'Divine Storm', max: 1, d: 'New in Forever — a holy whirlwind that strikes nearby enemies and heals the lowest-health ally near you.' },
      ] },
    ],
  },
  hunter: {
    trees: [
      { key: 'bm', name: 'Beast Mastery', icon: 'paw', talents: [
        { t: 0, name: 'Improved Aspect of the Hawk', max: 5, d: '+ ranged attack power from Aspect of the Hawk.' },
        { t: 0, name: 'Bestial Discipline', max: 2, d: '+ your pet\'s maximum focus/happiness pool.' },
        { t: 1, name: 'Pet Hardiness', max: 5, d: '+2% pet resistance to all schools per rank.' },
        { t: 1, name: 'Improved Mend Pet', max: 3, d: 'Mend Pet heals for more and can\'t be interrupted.' },
        { t: 2, name: 'Thick Hide', max: 3, d: '+2% pet armor per rank.' },
        { t: 2, name: 'Unleashed Fury', max: 5, d: '+ your pet\'s damage done.' },
        { t: 3, name: 'Ferocity', max: 5, d: '-cooldown on your pet\'s special abilities.' },
        { t: 3, name: 'Frenzy', max: 5, d: 'After a critical strike, your pet\'s attack speed increases for a few seconds.' },
        { t: 4, name: 'Bestial Swiftness', max: 1, d: '+ your pet\'s movement speed.' },
        { t: 5, name: 'Bestial Wrath', max: 1, d: 'Your pet goes berserk, dealing much more damage and becoming immune to crowd control for 18 sec.' },
        { t: 6, nf: true, name: 'Call of the Wild', max: 1, d: 'New in Forever — you and your pet both roar, boosting the attack power of the whole party for a short time.' },
      ] },
      { key: 'mm', name: 'Marksmanship', icon: 'bow', talents: [
        { t: 0, name: 'Improved Concussive Shot', max: 2, d: '+ snare duration from Concussive Shot.' },
        { t: 0, name: 'Efficiency', max: 5, d: '-1% mana cost of your abilities per rank.' },
        { t: 1, name: 'Improved Hunter\'s Mark', max: 3, d: 'Hunter\'s Mark also grants bonus critical strike chance against the target.' },
        { t: 1, name: 'Lethal Shots', max: 5, d: '+1% critical strike chance with ranged weapons per rank.' },
        { t: 2, name: 'Improved Arcane Shot', max: 3, d: 'Reduces the mana cost of Arcane Shot.' },
        { t: 2, name: 'Aimed Shot', max: 1, d: 'A powerful, slow-firing shot with high damage.' },
        { t: 3, name: 'Mortal Shots', max: 5, d: '+6% critical strike damage with ranged weapons per rank.' },
        { t: 3, name: 'Improved Serpent Sting', max: 3, d: 'Serpent Sting lasts longer.' },
        { t: 4, name: 'Barrage', max: 5, d: '-threat generated by your ranged attacks.' },
        { t: 5, name: 'Trueshot Aura', max: 1, d: 'An aura that boosts the attack power of your whole party.' },
        { t: 6, nf: true, name: 'Chimera Shot', max: 1, d: 'New in Forever — a shot that refreshes Serpent Sting and deals bonus damage based on it.' },
      ] },
      { key: 'surv', name: 'Survival', icon: 'trap', talents: [
        { t: 0, name: 'Monster Slaying', max: 3, d: '+ damage against Beasts and Dragonkin.' },
        { t: 0, name: 'Improved Wing Clip', max: 2, d: '+ snare chance from Wing Clip.' },
        { t: 1, name: 'Deflection', max: 5, d: '+1% parry chance per rank.' },
        { t: 1, name: 'Improved Freezing Trap', max: 2, d: 'Freezing Trap lasts longer.' },
        { t: 2, name: 'Deterrence', max: 1, d: 'Massively increases your dodge and parry chance for a few seconds.' },
        { t: 2, name: 'Survivalist', max: 5, d: '+2% maximum health per rank.' },
        { t: 3, name: 'Trap Mastery', max: 3, d: '+ effectiveness of your traps.' },
        { t: 3, name: 'Improved Feign Death', max: 2, d: '+ success chance on Feign Death.' },
        { t: 4, name: 'Counterattack', max: 1, d: 'After a dodge or parry, your next attack lands for extra damage.' },
        { t: 5, name: 'Wyvern Sting', max: 1, d: 'A sting that puts the target to sleep and causes damage over time if it wakes early.' },
        { t: 6, nf: true, name: 'Explosive Shot', max: 1, d: 'New in Forever — fires a shot that explodes for heavy damage over the next few seconds.' },
      ] },
    ],
  },
  rogue: {
    trees: [
      { key: 'assa', name: 'Assassination', icon: 'dagger-drip', talents: [
        { t: 0, name: 'Improved Eviscerate', max: 3, d: '+ damage done by Eviscerate.' },
        { t: 0, name: 'Malice', max: 5, d: '+1% critical strike chance per rank.' },
        { t: 1, name: 'Ruthlessness', max: 5, d: 'Finishing moves have a chance to grant a combo point back.' },
        { t: 1, name: 'Improved Slice and Dice', max: 3, d: 'Slice and Dice lasts longer.' },
        { t: 2, name: 'Lethality', max: 5, d: '+ critical strike damage with Sinister Strike and Backstab.' },
        { t: 2, name: 'Improved Expose Armor', max: 2, d: 'Expose Armor removes more armor.' },
        { t: 3, name: 'Cold Blood', max: 1, d: 'Your next attack is guaranteed to be a critical strike.' },
        { t: 3, name: 'Improved Poisons', max: 4, d: '+4% chance to apply your poisons per rank.' },
        { t: 4, name: 'Vigor', max: 1, d: '+ maximum energy.' },
        { t: 5, name: 'Seal Fate', max: 5, d: 'Critical strikes that award combo points grant an extra combo point.' },
        { t: 6, nf: true, name: 'Mutilate', max: 1, d: 'New in Forever — a vicious double stab from stealth that always strikes with both weapons.' },
      ] },
      { key: 'combat', name: 'Combat', icon: 'twin-blades', talents: [
        { t: 0, name: 'Improved Sinister Strike', max: 3, d: '-energy cost of Sinister Strike.' },
        { t: 0, name: 'Precision', max: 5, d: '+1% chance to hit per rank.' },
        { t: 1, name: 'Deflection', max: 5, d: '+1% parry chance per rank.' },
        { t: 1, name: 'Improved Sprint', max: 2, d: 'Reduces the cooldown of Sprint.' },
        { t: 2, name: 'Blade Flurry', max: 1, d: 'Your attacks also strike a nearby second target for a short time.' },
        { t: 2, name: 'Improved Kick', max: 3, d: 'Kick also silences the target\'s school for a few seconds.' },
        { t: 3, name: 'Dual Wield Specialization', max: 5, d: '+1% damage per rank with your off-hand weapon.' },
        { t: 3, name: 'Riposte', max: 1, d: 'A powerful counterattack available after a successful parry.' },
        { t: 4, name: 'Adrenaline Rush', max: 1, d: 'Doubles your energy regeneration for a short time.' },
        { t: 5, name: 'Blade Twisting', max: 2, d: '+ armor penetration with your weapons.' },
        { t: 6, nf: true, name: 'Killing Spree', max: 1, d: 'New in Forever — blink between nearby enemies, striking each one with both weapons.' },
      ] },
      { key: 'sub', name: 'Subtlety', icon: 'mask', talents: [
        { t: 0, name: 'Improved Gouge', max: 2, d: '+ duration of Gouge.' },
        { t: 0, name: 'Master of Deception', max: 5, d: '+ stealth detection avoidance.' },
        { t: 1, name: 'Improved Sap', max: 2, d: '+ duration of Sap.' },
        { t: 1, name: 'Opportunity', max: 5, d: '+ damage done from stealth per rank.' },
        { t: 2, name: 'Improved Backstab', max: 3, d: '+ damage done by Backstab.' },
        { t: 2, name: 'Premeditation', max: 1, d: 'From stealth, gain 2 combo points on your target in advance.' },
        { t: 3, name: 'Dirty Deeds', max: 2, d: '+ damage against targets below 35% health.' },
        { t: 3, name: 'Hemorrhage', max: 1, d: 'A strike that causes the target to bleed, increasing further damage taken.' },
        { t: 4, name: 'Improved Vanish', max: 2, d: 'Vanish removes more negative effects.' },
        { t: 5, name: 'Elusiveness', max: 2, d: '-cooldown on Cloak of Shadows and Vanish.' },
        { t: 6, nf: true, name: 'Shadowstep', max: 1, d: 'New in Forever — teleport behind your target in an instant, ready to strike.' },
      ] },
    ],
  },
  priest: {
    trees: [
      { key: 'disc', name: 'Discipline', icon: 'warding-cross', talents: [
        { t: 0, name: 'Unbreakable Will', max: 5, d: '+ resistance to stun and silence effects.' },
        { t: 0, name: 'Improved Power Word: Fortitude', max: 2, d: 'Power Word: Fortitude grants more stamina.' },
        { t: 1, name: 'Meditation', max: 3, d: 'Regenerate mana while casting.' },
        { t: 1, name: 'Improved Power Word: Shield', max: 3, d: '+ absorb amount on Power Word: Shield.' },
        { t: 2, name: 'Mental Agility', max: 5, d: '-mana cost of your instant cast spells.' },
        { t: 2, name: 'Improved Mana Burn', max: 2, d: 'Mana Burn has a chance to silence the target.' },
        { t: 3, name: 'Mental Strength', max: 5, d: '+ maximum mana.' },
        { t: 3, name: 'Power Infusion', max: 1, d: 'Temporarily increases the target\'s casting speed and reduces mana costs.' },
        { t: 4, name: 'Focused Will', max: 3, d: 'After being critically hit, take less damage for a few seconds.' },
        { t: 5, name: 'Inner Focus', max: 1, d: 'Your next spell costs no mana and has a greater effect.' },
        { t: 6, nf: true, name: 'Penance', max: 1, d: 'New in Forever — a channeled bolt of holy energy that heals an ally or damages an enemy in three quick volleys.' },
      ] },
      { key: 'holy', name: 'Holy', icon: 'sunburst', talents: [
        { t: 0, name: 'Healing Focus', max: 5, d: 'Chance not to be interrupted while healing.' },
        { t: 0, name: 'Improved Renew', max: 3, d: 'Renew heals for more.' },
        { t: 1, name: 'Holy Specialization', max: 5, d: '+1% critical strike chance with Holy spells per rank.' },
        { t: 1, name: 'Spell Warding', max: 5, d: '-damage taken from spells.' },
        { t: 2, name: 'Divine Fury', max: 5, d: '-cast time on Smite and Holy Fire.' },
        { t: 2, name: 'Spirit of Redemption', max: 1, d: 'Upon death, linger as a spirit for a short time, able to continue healing.' },
        { t: 3, name: 'Improved Prayer of Healing', max: 3, d: 'Reduces the mana cost of Prayer of Healing.' },
        { t: 3, name: 'Holy Reach', max: 2, d: '+ radius of your party-wide spells.' },
        { t: 4, name: 'Lightwell', max: 1, d: 'Summons a well that allies can click to heal themselves.' },
        { t: 5, name: 'Spiritual Guidance', max: 5, d: 'A portion of your Spirit is added to your spell damage/healing.' },
        { t: 6, nf: true, name: 'Circle of Healing', max: 1, d: 'New in Forever — an instant heal that jumps to several injured allies near the target.' },
      ] },
      { key: 'shadow', name: 'Shadow', icon: 'crescent-eye', talents: [
        { t: 0, name: 'Spirit Tap', max: 2, d: 'Killing a target grants bonus mana regeneration for a short time.' },
        { t: 0, name: 'Improved Shadow Word: Pain', max: 2, d: '+ duration of Shadow Word: Pain.' },
        { t: 1, name: 'Shadow Focus', max: 5, d: '-mana cost of your Shadow spells.' },
        { t: 1, name: 'Improved Psychic Scream', max: 2, d: 'Reduces the cooldown of Psychic Scream.' },
        { t: 2, name: 'Improved Mind Blast', max: 5, d: '-cooldown on Mind Blast.' },
        { t: 2, name: 'Mind Flay', max: 1, d: 'A channeled bolt of shadow energy that damages the target over time.' },
        { t: 3, name: 'Shadow Weaving', max: 5, d: 'Shadow spell hits stack a debuff that increases further shadow damage taken.' },
        { t: 3, name: 'Silence', max: 1, d: 'Silences the target, preventing spellcasting for a few seconds.' },
        { t: 4, name: 'Vampiric Embrace', max: 1, d: 'A portion of your shadow damage also heals your party.' },
        { t: 5, name: 'Shadowform', max: 1, d: 'Assume a shadowy form, boosting shadow damage and reducing damage taken.' },
        { t: 6, nf: true, name: 'Vampiric Touch', max: 1, d: 'New in Forever — a DoT that restores mana to the party whenever it deals damage.' },
      ] },
    ],
  },
  shaman: {
    trees: [
      { key: 'ele', name: 'Elemental', icon: 'lightning', talents: [
        { t: 0, name: 'Convection', max: 5, d: '-mana cost of your Shock and totem spells.' },
        { t: 0, name: 'Concussion', max: 5, d: '+1% damage with Shock spells per rank.' },
        { t: 1, name: 'Improved Fire Totems', max: 2, d: '+ effect of your Fire totems.' },
        { t: 1, name: 'Totemic Focus', max: 5, d: '-mana cost of totem spells.' },
        { t: 2, name: 'Call of Flame', max: 3, d: '+ damage done by Fire Nova Totem and Magma Totem.' },
        { t: 2, name: 'Improved Fire Nova Totem', max: 2, d: 'Reduces the cooldown of Fire Nova Totem.' },
        { t: 3, name: 'Elemental Focus', max: 1, d: 'After a critical spell, your next spells cost less mana.' },
        { t: 3, name: 'Reverberation', max: 5, d: '-cooldown on your Shock spells.' },
        { t: 4, name: 'Elemental Fury', max: 5, d: '+ critical strike damage with elemental spells per rank.' },
        { t: 5, name: 'Elemental Mastery', max: 1, d: 'Your next spell is cast instantly and guaranteed to critically strike.' },
        { t: 6, nf: true, name: 'Lava Burst', max: 1, d: 'New in Forever — a bolt of lava that is guaranteed to critically strike any target affected by your Flame Shock.' },
      ] },
      { key: 'enh', name: 'Enhancement', icon: 'fist-spark', talents: [
        { t: 0, name: 'Improved Lightning Shield', max: 5, d: '+ damage from Lightning Shield charges.' },
        { t: 0, name: 'Shield Specialization', max: 5, d: '+1% chance to block per rank.' },
        { t: 1, name: 'Guardian Totems', max: 2, d: '+ effect of your Stoneskin and Stoneclaw totems.' },
        { t: 1, name: 'Thundering Strikes', max: 5, d: '+1% critical strike chance per rank.' },
        { t: 2, name: 'Improved Weapon Totems', max: 3, d: '+ effect of your weapon totems.' },
        { t: 2, name: 'Flurry', max: 5, d: 'After a critical strike, attack speed is increased for your next few swings.' },
        { t: 3, name: 'Elemental Weapons', max: 3, d: '+ effect of temporary weapon enchants.' },
        { t: 3, name: 'Spirit Weapons', max: 1, d: 'Melee attacks no longer cause threat, but your attack speed decreases.' },
        { t: 4, name: 'Mental Quickness', max: 5, d: 'A portion of your attack power is added to your spell damage.' },
        { t: 5, name: 'Stormstrike', max: 1, d: 'A melee strike that also boosts your next two Nature spell hits against the target.' },
        { t: 6, nf: true, name: 'Lava Lash', max: 1, d: 'New in Forever — an off-hand strike dealing bonus fire damage, boosted if your weapon is flametongue-enchanted.' },
      ] },
      { key: 'resto', name: 'Restoration', icon: 'droplet', talents: [
        { t: 0, name: 'Improved Healing Wave', max: 5, d: 'Reduces the cast time of Healing Wave.' },
        { t: 0, name: 'Totemic Focus', max: 5, d: '-mana cost of totem spells.' },
        { t: 1, name: 'Improved Reincarnation', max: 2, d: 'Reduces the cooldown of Reincarnation.' },
        { t: 1, name: 'Totemic Mastery', max: 1, d: '+ radius of all your totem effects.' },
        { t: 2, name: 'Improved Water Shield', max: 3, d: '+ effect of Water Shield.' },
        { t: 2, name: 'Nature\'s Guidance', max: 3, d: '+1% chance to hit with spells and attacks per rank.' },
        { t: 3, name: 'Healing Focus', max: 5, d: 'Chance not to be interrupted while healing.' },
        { t: 3, name: 'Nature\'s Swiftness', max: 1, d: 'Your next Nature spell is cast instantly.' },
        { t: 4, name: 'Improved Chain Heal', max: 2, d: 'Chain Heal jumps to more targets.' },
        { t: 5, name: 'Mana Tide Totem', max: 1, d: 'A totem that greatly boosts party mana regeneration for a short time.' },
        { t: 6, nf: true, name: 'Riptide', max: 1, d: 'New in Forever — an instant heal that also leaves a heal-over-time on the target.' },
      ] },
    ],
  },
  mage: {
    trees: [
      { key: 'arcane', name: 'Arcane', icon: 'star-burst', talents: [
        { t: 0, name: 'Arcane Subtlety', max: 2, d: '-threat generated by your Arcane spells.' },
        { t: 0, name: 'Arcane Focus', max: 5, d: '-mana cost of your Arcane spells.' },
        { t: 1, name: 'Improved Arcane Missiles', max: 3, d: 'Chance not to be interrupted while channeling Arcane Missiles.' },
        { t: 1, name: 'Arcane Concentration', max: 5, d: 'Critical spell hits have a chance to make your next spell instant.' },
        { t: 2, name: 'Magic Absorption', max: 5, d: '+ resistance to all magic schools.' },
        { t: 2, name: 'Arcane Meditation', max: 3, d: 'Regenerate mana while casting.' },
        { t: 3, name: 'Presence of Mind', max: 1, d: 'Your next spell is cast instantly.' },
        { t: 3, name: 'Arcane Mind', max: 5, d: '+ maximum mana.' },
        { t: 4, name: 'Improved Counterspell', max: 2, d: 'Counterspell silences the target for longer.' },
        { t: 5, name: 'Arcane Power', max: 1, d: 'Temporarily increases spell damage, at the cost of increased mana costs.' },
        { t: 6, nf: true, name: 'Mirror Image', max: 1, d: 'New in Forever — summons two decoys of yourself that mimic your spells and draw enemy attention.' },
      ] },
      { key: 'fire', name: 'Fire', icon: 'flame', talents: [
        { t: 0, name: 'Improved Fireball', max: 5, d: 'Reduces the cast time of Fireball.' },
        { t: 0, name: 'Impact', max: 5, d: 'Fire spells have a chance to stun the target.' },
        { t: 1, name: 'Ignite', max: 5, d: 'Critical fire hits leave a burning DoT on the target.' },
        { t: 1, name: 'Flame Throwing', max: 2, d: '+ range of your fire spells.' },
        { t: 2, name: 'Improved Fire Blast', max: 3, d: 'Reduces the cooldown of Fire Blast.' },
        { t: 2, name: 'Incineration', max: 2, d: '+ critical strike damage with fire spells.' },
        { t: 3, name: 'Pyroblast', max: 1, d: 'A very powerful, slow-casting fire spell.' },
        { t: 3, name: 'Burning Soul', max: 5, d: '-threat generated by your fire spells.' },
        { t: 4, name: 'Fire Power', max: 5, d: '+1% fire spell damage per rank.' },
        { t: 5, name: 'Combustion', max: 1, d: 'Your next few spells are guaranteed to critically strike.' },
        { t: 6, nf: true, name: 'Living Bomb', max: 1, d: 'New in Forever — plants a DoT on the target that explodes for AoE damage when it ends or the target dies.' },
      ] },
      { key: 'frost', name: 'Frost', icon: 'snowflake', talents: [
        { t: 0, name: 'Improved Frostbolt', max: 5, d: 'Reduces the cast time of Frostbolt.' },
        { t: 0, name: 'Elemental Precision', max: 3, d: '+1% chance to hit with Fire and Frost spells per rank.' },
        { t: 1, name: 'Ice Shards', max: 5, d: '+ critical strike damage with frost spells.' },
        { t: 1, name: 'Frostbite', max: 3, d: 'Frost spells have a chance to freeze the target in place.' },
        { t: 2, name: 'Improved Frost Nova', max: 2, d: 'Reduces the cooldown of Frost Nova.' },
        { t: 2, name: 'Permafrost', max: 3, d: 'Frozen targets are slowed for longer after thawing.' },
        { t: 3, name: 'Ice Barrier', max: 1, d: 'A shield that absorbs damage for a short time.' },
        { t: 3, name: 'Improved Blizzard', max: 3, d: 'Blizzard has a chance to stun the target.' },
        { t: 4, name: 'Frost Channeling', max: 5, d: '-mana cost of your frost spells.' },
        { t: 5, name: 'Winter\'s Chill', max: 1, d: 'Frost spells reduce the target\'s resistance to further frost damage.' },
        { t: 6, nf: true, name: 'Deep Freeze', max: 1, d: 'New in Forever — stuns a frozen target and deals heavy bonus damage while it lasts.' },
      ] },
    ],
  },
  warlock: {
    trees: [
      { key: 'affl', name: 'Affliction', icon: 'skull-wisp', talents: [
        { t: 0, name: 'Improved Corruption', max: 5, d: 'Reduces the cast time of Corruption.' },
        { t: 0, name: 'Suppression', max: 2, d: '+1% chance to hit with Affliction spells per rank.' },
        { t: 1, name: 'Improved Curse of Agony', max: 2, d: '+ damage done by Curse of Agony.' },
        { t: 1, name: 'Improved Drain Soul', max: 2, d: '+ damage done by Drain Soul.' },
        { t: 2, name: 'Improved Life Tap', max: 2, d: 'Life Tap returns more mana.' },
        { t: 2, name: 'Fel Concentration', max: 5, d: 'Chance not to be interrupted while channeling drain effects.' },
        { t: 3, name: 'Nightfall', max: 2, d: 'Corruption and Drain Life have a chance to grant a free instant Shadow Bolt.' },
        { t: 3, name: 'Empowered Corruption', max: 3, d: 'Corruption gains more benefit from your spell damage.' },
        { t: 4, name: 'Shadow Mastery', max: 5, d: '+1% shadow spell damage per rank.' },
        { t: 5, name: 'Dark Pact', max: 1, d: 'Drains mana from your summoned demon instead of yourself.' },
        { t: 6, nf: true, name: 'Haunt', max: 1, d: 'New in Forever — a shadow bolt that boosts the damage of your DoTs on the target and returns health when it dies.' },
      ] },
      { key: 'demo', name: 'Demonology', icon: 'demon-horns', talents: [
        { t: 0, name: 'Improved Healthstone', max: 2, d: 'Healthstone heals for more.' },
        { t: 0, name: 'Improved Imp', max: 3, d: '+ Imp\'s Firebolt damage and resistance.' },
        { t: 1, name: 'Demonic Embrace', max: 5, d: '+ maximum health, -maximum mana per rank.' },
        { t: 1, name: 'Improved Voidwalker', max: 3, d: '+ Voidwalker health and threat generation.' },
        { t: 2, name: 'Fel Intellect', max: 3, d: '+ maximum mana for you and your demon.' },
        { t: 2, name: 'Improved Succubus', max: 3, d: '+ Succubus\'s Seduction effect.' },
        { t: 3, name: 'Fel Domination', max: 1, d: 'Your next demon summon is instant.' },
        { t: 3, name: 'Demonic Sacrifice', max: 1, d: 'Sacrifice your demon for a lasting personal bonus.' },
        { t: 4, name: 'Master Summoner', max: 2, d: '-cast time and mana cost of demon summoning spells.' },
        { t: 5, name: 'Master Demonologist', max: 5, d: 'Grants a bonus based on which demon you currently have summoned.' },
        { t: 6, nf: true, name: 'Metamorphosis', max: 1, d: 'New in Forever — transform into a demon yourself, boosting damage and survivability for a short time.' },
      ] },
      { key: 'destro', name: 'Destruction', icon: 'fireball', talents: [
        { t: 0, name: 'Improved Shadow Bolt', max: 5, d: 'Shadow Bolt hits weaken the target against your next spell.' },
        { t: 0, name: 'Cataclysm', max: 5, d: '-mana cost of your Destruction spells.' },
        { t: 1, name: 'Bane', max: 5, d: 'Reduces the cast time of your Destruction spells.' },
        { t: 1, name: 'Improved Firebolt', max: 2, d: '+ Imp\'s Firebolt damage.' },
        { t: 2, name: 'Devastation', max: 5, d: '+1% critical strike chance with Destruction spells per rank.' },
        { t: 2, name: 'Shadowburn', max: 1, d: 'An instant spell that refunds a soul shard if it kills the target.' },
        { t: 3, name: 'Intensity', max: 3, d: 'Chance not to be interrupted when taking damage while casting.' },
        { t: 3, name: 'Destructive Reach', max: 2, d: '+ range of your Destruction spells.' },
        { t: 4, name: 'Pyroclasm', max: 2, d: 'After a stun, +critical strike chance for a few seconds.' },
        { t: 5, name: 'Ruin', max: 1, d: '+100% critical strike damage with Destruction spells.' },
        { t: 6, nf: true, name: 'Chaos Bolt', max: 1, d: 'New in Forever — an unstoppable bolt of pure chaos that cannot be resisted, reflected or absorbed.' },
      ] },
    ],
  },
  druid: {
    trees: [
      { key: 'balance', name: 'Balance', icon: 'moon-sun', talents: [
        { t: 0, name: 'Improved Wrath', max: 3, d: 'Reduces the cast time of Wrath.' },
        { t: 0, name: 'Improved Moonfire', max: 2, d: 'Reduces the mana cost of Moonfire.' },
        { t: 1, name: 'Improved Thorns', max: 2, d: 'Thorns lasts longer.' },
        { t: 1, name: 'Starlight Wrath', max: 5, d: 'Reduces the cast time of Moonfire, Starfire and Wrath.' },
        { t: 2, name: 'Nature\'s Grace', max: 1, d: 'After a critical spell, your next cast is faster.' },
        { t: 2, name: 'Vengeance', max: 5, d: '+ critical strike damage with Arcane and Nature spells.' },
        { t: 3, name: 'Moonfury', max: 5, d: '+1% Arcane and Nature spell damage per rank.' },
        { t: 3, name: 'Moonglow', max: 3, d: '-mana cost of your main healing and nuking spells.' },
        { t: 4, name: 'Insect Swarm', max: 1, d: 'A DoT that reduces the target\'s chance to hit you.' },
        { t: 5, name: 'Force of Nature', max: 1, d: 'Summons treants that fight at your side for a short time.' },
        { t: 6, nf: true, name: 'Starfall', max: 1, d: 'New in Forever — calls down falling stars that smash into enemies around you over several seconds.' },
      ] },
      { key: 'feral', name: 'Feral Combat', icon: 'claw', talents: [
        { t: 0, name: 'Ferocity', max: 5, d: '-rage/energy cost of several feral abilities.' },
        { t: 0, name: 'Feral Aggression', max: 5, d: '+ damage done by Maul and Swipe.' },
        { t: 1, name: 'Thick Hide', max: 3, d: '+ armor value while in Bear Form.' },
        { t: 1, name: 'Feral Instinct', max: 5, d: '+ threat generated in Bear Form, +dodge chance in Cat Form.' },
        { t: 2, name: 'Sharpened Claws', max: 3, d: '+1% critical strike chance in Bear/Cat Form per rank.' },
        { t: 2, name: 'Feral Charge', max: 1, d: 'Charges an enemy and stuns it on impact (Bear or Cat Form).' },
        { t: 3, name: 'Improved Shred', max: 3, d: '+ damage done by Shred.' },
        { t: 3, name: 'Predatory Strikes', max: 3, d: '+ attack power based on your level while shapeshifted.' },
        { t: 4, name: 'Faerie Fire (Feral)', max: 1, d: 'An instant ranged attack that also exposes the target\'s armor.' },
        { t: 5, name: 'Mangle', max: 1, d: 'A vicious attack dealing heavy damage and causing further bleed damage to stack higher.' },
        { t: 6, nf: true, name: 'Berserk', max: 1, d: 'New in Forever — removes the cooldown on several of your core abilities for a short time.' },
      ] },
      { key: 'resto', name: 'Restoration', icon: 'droplet', talents: [
        { t: 0, name: 'Improved Mark of the Wild', max: 2, d: 'Mark of the Wild grants a larger bonus.' },
        { t: 0, name: 'Nature\'s Grasp', max: 1, d: 'Summons a root effect on the next enemy that attacks you in melee.' },
        { t: 1, name: 'Improved Healing Touch', max: 5, d: 'Reduces the cast time of Healing Touch.' },
        { t: 1, name: 'Furor', max: 5, d: 'Chance to gain energy/rage when shapeshifting.' },
        { t: 2, name: 'Tranquil Spirit', max: 5, d: '-mana cost of Healing Touch and Tranquility.' },
        { t: 2, name: 'Improved Rejuvenation', max: 4, d: 'Rejuvenation heals for more.' },
        { t: 3, name: 'Nature\'s Swiftness', max: 1, d: 'Your next Nature spell is cast instantly.' },
        { t: 3, name: 'Gift of Nature', max: 5, d: '+ healing done by all your spells.' },
        { t: 4, name: 'Improved Regrowth', max: 5, d: '+1% critical effect chance with Regrowth per rank.' },
        { t: 5, name: 'Tranquility', max: 1, d: 'A powerful channeled heal that restores the entire party over time.' },
        { t: 6, nf: true, name: 'Wild Growth', max: 1, d: 'New in Forever — an instant heal-over-time that lands on several injured allies near the target at once.' },
      ] },
    ],
  },
};

// Walks each tree in order and spends points top-down, maxing each talent before moving on —
// generates the recommended builds and their shareable calculator link.
export function greedyAllocate(classSlug, order, budget = 51) {
  const trees = TALENT_TREES[classSlug].trees;
  const ranks = trees.map((t) => t.talents.map(() => 0));
  const spent = trees.map(() => 0);
  let remaining = budget;
  for (const ti of order) {
    const tree = trees[ti];
    const maxTier = Math.max(...tree.talents.map((t) => t.t));
    for (let tier = 0; tier <= maxTier; tier++) {
      if (spent[ti] < tier * 5) break;
      tree.talents.forEach((tal, idx) => {
        if (tal.t !== tier || remaining <= 0) return;
        const add = Math.min(tal.max, remaining);
        ranks[ti][idx] = add;
        spent[ti] += add;
        remaining -= add;
      });
    }
  }
  const hash = ranks.map((r) => r.join('')).join('-');
  const picks = trees.map((tree, ti) => tree.talents
    .map((tal, idx) => ({ name: tal.name, rank: ranks[ti][idx], max: tal.max }))
    .filter((p) => p.rank > 0));
  return { hash, picks, spent, totalSpent: budget - remaining };
}

// Rough builds inspired by well-known community leveling/raid specs (Wowhead Classic, Icy Veins and
// others), recomputed on our own calculator — exact point counts differ from those sources since our
// trees are a condensed, original version.
export const BUILD_PLAN = [
  { slug: 'warrior', level: { order: [1, 0, 2], label: 'Fury', note: 'Dual-wield so sústavným poškodením uľahčuje sólo levelovanie a farmenie.' }, raid: { order: [2, 0, 1], label: 'Protection', note: 'Najžiadanejšia rola warriora v raide — tank s vysokým brnením a threatom.' } },
  { slug: 'paladin', level: { order: [2, 0, 1], label: 'Retribution', note: 'Seal of Command a melee sila zrýchlia levelovanie aj sólo questing.' }, raid: { order: [0, 2, 1], label: 'Holy', note: 'Primárna raidová rola paladina — masové a spoľahlivé liečenie.' } },
  { slug: 'hunter', level: { order: [0, 2, 1], label: 'Beast Mastery', note: 'Silný a odolný pet výrazne znižuje riziko pri sólo levelovaní.' }, raid: { order: [1, 0, 2], label: 'Marksmanship', note: 'Najvyšší stabilný ranged damage na dlhé raidové fighty.' } },
  { slug: 'rogue', level: { order: [1, 0, 2], label: 'Combat', note: 'Vyššia výdrž a damage v dlhších súbojoch počas levelovania.' }, raid: { order: [0, 1, 2], label: 'Assassination', note: 'Jedy a combo body dávajú v raide stabilný a vysoký damage.' } },
  { slug: 'priest', level: { order: [2, 0, 1], label: 'Shadow', note: 'Vlastný damage a drain many uľahčia bezpečné sólo hranie.' }, raid: { order: [1, 0, 2], label: 'Holy', note: 'Primárna raidová rola priesta — hlavný liečiteľ skupiny.' } },
  { slug: 'shaman', level: { order: [1, 0, 2], label: 'Enhancement', note: 'Melee sila a Windfury pomáhajú rýchlejšie zabíjať pri levelovaní.' }, raid: { order: [2, 0, 1], label: 'Restoration', note: 'Chain Heal a totemy z neho robia kľúčového raidového healera.' } },
  { slug: 'mage', level: { order: [1, 2, 0], label: 'Fire', note: 'Vysoký burst a AoE farmenie celých packov zrýchli levelovanie.' }, raid: { order: [1, 0, 2], label: 'Fire', note: 'Štandardná raidová špecializácia mága vo vanille.' } },
  { slug: 'warlock', level: { order: [0, 1, 2], label: 'Affliction', note: 'DoT kúzla a Drain Life umožňujú bezpečné a pohodlné sólo levelovanie.' }, raid: { order: [2, 0, 1], label: 'Destruction', note: 'Shadowburn a Ruin dávajú v raide silný burst damage.' } },
  { slug: 'druid', level: { order: [1, 2, 0], label: 'Feral', note: 'Medveď na tankovanie, mačka na damage — flexibilita pri sólo hraní.' }, raid: { order: [2, 0, 1], label: 'Restoration', note: 'Primárna raidová rola druida — HoT liečenie celej skupiny.' } },
];
